/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitap;

import java.awt.Graphics;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/**
 *
 * @author Apple Bee
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.WHITE);
        jPanel_KhungVe.setBackground(Color.BLUE);
//        System.out.println(jPanel_KhungVe.getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_KhungVe = new javax.swing.JPanel(){
            private static final long serialVersionUID = 1L;
            @Override
            protected void paintComponent(Graphics arg0) {
                // TODO Auto-generated method stub
                super.paintComponent(arg0);
                arg0.setColor(Color.LIGHT_GRAY);
                for (int i = 5; i< BasicParam.backgroundWidth; i += 5) {
                    arg0.drawLine(i,0,i,BasicParam.backgroundHeight);
                }
                for (int i = 5; i< BasicParam.backgroundHeight; i += 5) {
                    arg0.drawLine(0,i,BasicParam.backgroundWidth, i);
                }
                setBackground(Color.WHITE);
                arg0.setColor(Color.BLACK);
                arg0.drawString("O", BasicParam.backgroundWidth/2 + 5, BasicParam.backgroundHeight/2 + 20);
                arg0.drawString("10", BasicParam.backgroundWidth/2 + 50, BasicParam.backgroundHeight/2 + 20);
                arg0.drawString("20", BasicParam.backgroundWidth/2 + 100, BasicParam.backgroundHeight/2 + 20);
                arg0.drawString("30", BasicParam.backgroundWidth/2 + 150, BasicParam.backgroundHeight/2 + 20);
                arg0.drawString("40", BasicParam.backgroundWidth/2 + 200, BasicParam.backgroundHeight/2 + 20);
                arg0.drawString("x", BasicParam.backgroundWidth - 5, BasicParam.backgroundHeight/2 + 20);
                arg0.drawString("y", BasicParam.backgroundWidth/2 + 5, 20);
                arg0.drawString(">", BasicParam.backgroundWidth, BasicParam.backgroundHeight/2 + 5);
                arg0.drawString("/\\", BasicParam.backgroundWidth/2 - 3, 10);
                    //        arg0.drawString("z", 5, BasicParam.backgroundHeight - 20);
                    arg0.drawLine(BasicParam.backgroundWidth/2, 0, BasicParam.backgroundWidth/2, BasicParam.backgroundHeight/2);//y+
                    for (int i = 1; i < BasicParam.backgroundWidth/100; i++) { //vach don vi
                        arg0.drawLine(BasicParam.backgroundWidth/2 + i * 50, BasicParam.backgroundHeight/2 - 2, BasicParam.backgroundWidth/2 + i * 50, BasicParam.backgroundHeight/2 + 2);
                    }
                    for (int i = 1; i < BasicParam.backgroundHeight/100; i++) { //vach don vi
                        arg0.drawLine(BasicParam.backgroundWidth/2 - 2, i * 50, BasicParam.backgroundWidth/2 + 2, i * 50);
                    }
                    arg0.setColor(Color.BLUE);
                    for(int i=BasicParam.backgroundHeight/2;i<=BasicParam.backgroundHeight;i+=6){//y-
                        arg0.drawLine(BasicParam.backgroundWidth/2, i, BasicParam.backgroundWidth/2,i+3);
                    }
                    arg0.setColor(Color.BLACK);
                    arg0.drawLine(BasicParam.backgroundWidth/2, BasicParam.backgroundHeight/2, BasicParam.backgroundWidth, BasicParam.backgroundHeight/2);//x+
                    arg0.setColor(Color.BLUE);
                    for(int i=BasicParam.backgroundWidth/2;i>=0;i-=6){//x-
                        arg0.drawLine(i,BasicParam.backgroundHeight/2,i-3,BasicParam.backgroundHeight/2);
                    }

                    //        arg0.setColor(Color.BLACK);
                    //        arg0.drawLine(0,BasicParam.backgroundHeight,BasicParam.backgroundWidth/2,BasicParam.backgroundHeight/2);//z+
                    //        int l = BasicParam.backgroundHeight / 2;
                    //        arg0.setColor(Color.GREEN);
                    //        for (int i = BasicParam.backgroundWidth / 2; i <= BasicParam.backgroundWidth; i += 6) {
                        //            arg0.drawLine(i + 3, l - 3, i + 6, l - 6);
                        //            l -= 6;
                        //        }
                }
            };
            jLabel8 = new javax.swing.JLabel();
            jTabbedPane1 = new javax.swing.JTabbedPane();
            Diem = new javax.swing.JPanel();
            jLabel12 = new javax.swing.JLabel();
            jTextField_x = new javax.swing.JTextField();
            jTextField_y = new javax.swing.JTextField();
            jLabel13 = new javax.swing.JLabel();
            jButton_VeDiem = new javax.swing.JButton();
            DoanThang = new javax.swing.JPanel();
            jTextField_x1 = new javax.swing.JTextField();
            jLabel1 = new javax.swing.JLabel();
            jLabel2 = new javax.swing.JLabel();
            jLabel3 = new javax.swing.JLabel();
            jLabel4 = new javax.swing.JLabel();
            jTextField_y1 = new javax.swing.JTextField();
            jTextField_x2 = new javax.swing.JTextField();
            jTextField_y2 = new javax.swing.JTextField();
            jPanel1 = new javax.swing.JPanel();
            jButton_VeDoanThang = new javax.swing.JButton();
            jButton_VeNetDut = new javax.swing.JButton();
            jButton_NetChamGach = new javax.swing.JButton();
            jButton_NetHaiChamGach = new javax.swing.JButton();
            jButton_VeMuiTen = new javax.swing.JButton();
            jButton_VeHinhChuNhat = new javax.swing.JButton();
            TamGiacDeu = new javax.swing.JPanel();
            jTextField_xDinh = new javax.swing.JTextField();
            jLabel9 = new javax.swing.JLabel();
            jLabel10 = new javax.swing.JLabel();
            jTextField_yDinh = new javax.swing.JTextField();
            jLabel11 = new javax.swing.JLabel();
            jTextField_canh = new javax.swing.JTextField();
            jButton_VeTamGiac = new javax.swing.JButton();
            HinhTron = new javax.swing.JPanel();
            jLabel5 = new javax.swing.JLabel();
            jLabel6 = new javax.swing.JLabel();
            jTextField_xO = new javax.swing.JTextField();
            jTextField_yO = new javax.swing.JTextField();
            jButton_VeDuongTron = new javax.swing.JButton();
            jLabel7 = new javax.swing.JLabel();
            jTextField_r = new javax.swing.JTextField();
            Ellipse = new javax.swing.JPanel();
            jLabel14 = new javax.swing.JLabel();
            jTextField_xC = new javax.swing.JTextField();
            jLabel15 = new javax.swing.JLabel();
            jTextField_yC = new javax.swing.JTextField();
            jTextField_a = new javax.swing.JTextField();
            jLabel16 = new javax.swing.JLabel();
            jButton_VeEllipse = new javax.swing.JButton();
            jLabel17 = new javax.swing.JLabel();
            jTextField_b = new javax.swing.JTextField();
            jButton_Xoa = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(0, 204, 255));
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel_KhungVe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout jPanel_KhungVeLayout = new javax.swing.GroupLayout(jPanel_KhungVe);
            jPanel_KhungVe.setLayout(jPanel_KhungVeLayout);
            jPanel_KhungVeLayout.setHorizontalGroup(
                jPanel_KhungVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 508, Short.MAX_VALUE)
            );
            jPanel_KhungVeLayout.setVerticalGroup(
                jPanel_KhungVeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );

            getContentPane().add(jPanel_KhungVe, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 510, 500));

            jLabel8.setForeground(new java.awt.Color(153, 153, 153));
            jLabel8.setText("1 đơn vị = 5 pixel");
            getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            jTabbedPane1.setBackground(new java.awt.Color(0, 204, 255));

            Diem.setBackground(new java.awt.Color(0, 204, 255));
            Diem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel12.setText("x:");
            Diem.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, -1));
            Diem.add(jTextField_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 112, -1));
            Diem.add(jTextField_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 112, -1));

            jLabel13.setText("y:");
            Diem.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

            jButton_VeDiem.setText("Vẽ điểm");
            jButton_VeDiem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDiemActionPerformed(evt);
                }
            });
            Diem.add(jButton_VeDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, 40));

            jTabbedPane1.addTab("Điểm", Diem);

            DoanThang.setBackground(new java.awt.Color(0, 204, 255));
            DoanThang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            DoanThang.add(jTextField_x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 116, -1));

            jLabel1.setText("x1:");
            DoanThang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

            jLabel2.setText("y1:");
            DoanThang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

            jLabel3.setText("x2:");
            DoanThang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, -1, -1));

            jLabel4.setText("y2:");
            DoanThang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));
            DoanThang.add(jTextField_y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 116, -1));
            DoanThang.add(jTextField_x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 116, -1));
            DoanThang.add(jTextField_y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 116, -1));

            jPanel1.setBackground(new java.awt.Color(0, 204, 255));
            jPanel1.setLayout(new java.awt.GridLayout(6, 1, 0, 10));

            jButton_VeDoanThang.setText("Vẽ đoạn thẳng");
            jButton_VeDoanThang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDoanThangActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_VeDoanThang);

            jButton_VeNetDut.setText("Vẽ nét đứt");
            jButton_VeNetDut.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeNetDutActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_VeNetDut);

            jButton_NetChamGach.setText("Vẽ nét chấm gạch");
            jButton_NetChamGach.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_NetChamGachActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_NetChamGach);

            jButton_NetHaiChamGach.setText("Vẽ nét hai chấm gạch");
            jButton_NetHaiChamGach.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_NetHaiChamGachActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_NetHaiChamGach);

            jButton_VeMuiTen.setText("Vẽ mũi tên");
            jButton_VeMuiTen.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeMuiTenActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_VeMuiTen);

            jButton_VeHinhChuNhat.setText("Vẽ hình chữ nhật");
            jButton_VeHinhChuNhat.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhChuNhatActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_VeHinhChuNhat);

            DoanThang.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 160, 230));

            jTabbedPane1.addTab("Đoạn thẳng", DoanThang);

            TamGiacDeu.setBackground(new java.awt.Color(0, 204, 255));
            TamGiacDeu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            TamGiacDeu.add(jTextField_xDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 112, -1));

            jLabel9.setText("x đỉnh:");
            TamGiacDeu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

            jLabel10.setText("y đỉnh:");
            TamGiacDeu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));
            TamGiacDeu.add(jTextField_yDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 112, -1));

            jLabel11.setText("a:");
            TamGiacDeu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
            TamGiacDeu.add(jTextField_canh, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 112, -1));

            jButton_VeTamGiac.setText("Vẽ tam giác");
            jButton_VeTamGiac.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeTamGiacActionPerformed(evt);
                }
            });
            TamGiacDeu.add(jButton_VeTamGiac, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 160, 40));

            jTabbedPane1.addTab("Tam giác đều", TamGiacDeu);

            HinhTron.setBackground(new java.awt.Color(0, 204, 255));
            HinhTron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel5.setText("xO:");
            HinhTron.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

            jLabel6.setText("yO:");
            HinhTron.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, -1));
            HinhTron.add(jTextField_xO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 112, -1));
            HinhTron.add(jTextField_yO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 112, -1));

            jButton_VeDuongTron.setText("Vẽ đường tròn");
            jButton_VeDuongTron.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDuongTronActionPerformed(evt);
                }
            });
            HinhTron.add(jButton_VeDuongTron, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 30));

            jLabel7.setText("r:");
            HinhTron.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));
            HinhTron.add(jTextField_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 112, -1));

            jTabbedPane1.addTab("Đường tròn", HinhTron);

            jLabel14.setText("xO:");

            jLabel15.setText("yO:");

            jLabel16.setText("a:");

            jButton_VeEllipse.setText("Vẽ Ellipse");
            jButton_VeEllipse.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeEllipseActionPerformed(evt);
                }
            });

            jLabel17.setText("b:");

            javax.swing.GroupLayout EllipseLayout = new javax.swing.GroupLayout(Ellipse);
            Ellipse.setLayout(EllipseLayout);
            EllipseLayout.setHorizontalGroup(
                EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EllipseLayout.createSequentialGroup()
                    .addContainerGap(111, Short.MAX_VALUE)
                    .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EllipseLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField_b, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EllipseLayout.createSequentialGroup()
                                .addComponent(jButton_VeEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(114, 114, 114))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EllipseLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_a, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)))))
                .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EllipseLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EllipseLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(2, 2, 2)
                                .addComponent(jTextField_xC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EllipseLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(2, 2, 2)
                                .addComponent(jTextField_yC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
            );
            EllipseLayout.setVerticalGroup(
                EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EllipseLayout.createSequentialGroup()
                    .addGap(151, 151, 151)
                    .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGap(18, 18, 18)
                    .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jTextField_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(71, 71, 71)
                    .addComponent(jButton_VeEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(112, Short.MAX_VALUE))
                .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EllipseLayout.createSequentialGroup()
                        .addGap(0, 66, Short.MAX_VALUE)
                        .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jTextField_xC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jTextField_yC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 306, Short.MAX_VALUE)))
            );

            jTabbedPane1.addTab("Ellipse", Ellipse);

            getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 360, 450));

            jButton_Xoa.setText("Xóa");
            jButton_Xoa.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_XoaActionPerformed(evt);
                }
            });
            getContentPane().add(jButton_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 50, 30));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton_VeDoanThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDoanThangActionPerformed
        // TODO add your handling code here:
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText())*5;
            int y1 = Integer.parseInt(jTextField_y1.getText())*5;
            int x2 = Integer.parseInt(jTextField_x2.getText())*5;
            int y2 = Integer.parseInt(jTextField_y2.getText())*5;
            DoanThang m = new DoanThang(x1, y1, x2, y2); 
//            jPanel_KhungVe.removeAll();
            jPanel_KhungVe.add(m.draw());
            jPanel_KhungVe.revalidate();
            jPanel_KhungVe.repaint();
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");    
    }//GEN-LAST:event_jButton_VeDoanThangActionPerformed

    private void jButton_VeHinhChuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhChuNhatActionPerformed
        // TODO add your handling code here:
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText())*5;
            int y1 = Integer.parseInt(jTextField_y1.getText())*5;
            int x2 = Integer.parseInt(jTextField_x2.getText())*5;
            int y2 = Integer.parseInt(jTextField_y2.getText())*5;
            HinhChuNhat m = new HinhChuNhat(x1, y1, x2, y2); 
//            jPanel_KhungVe.removeAll();
            jPanel_KhungVe.add(m.draw());
            jPanel_KhungVe.revalidate();
            jPanel_KhungVe.repaint(); 
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeHinhChuNhatActionPerformed

    private void jButton_VeDuongTronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDuongTronActionPerformed
        // TODO add your handling code here:
        if (rangBuocDuLieuDuongTron() == true) {
            int xO = Integer.parseInt(jTextField_xO.getText())*5;
            int yO = Integer.parseInt(jTextField_yO.getText())*5;
            int r = Integer.parseInt(jTextField_r.getText())*5;
            DuongTron m = new DuongTron(xO, yO, r); 
//            jPanel_KhungVe.removeAll();
            jPanel_KhungVe.add(m.draw());
            jPanel_KhungVe.revalidate();
            jPanel_KhungVe.repaint();
            System.out.println(jPanel_KhungVe.getBounds());
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeDuongTronActionPerformed

    private void jButton_VeNetDutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeNetDutActionPerformed
        // TODO add your handling code here:
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText())*5;
            int y1 = Integer.parseInt(jTextField_y1.getText())*5;
            int x2 = Integer.parseInt(jTextField_x2.getText())*5;
            int y2 = Integer.parseInt(jTextField_y2.getText())*5;
            NetDut m = new NetDut(x1, y1, x2, y2);
//            jPanel_KhungVe.removeAll();
            jPanel_KhungVe.add(m.draw());
            jPanel_KhungVe.revalidate();
            jPanel_KhungVe.repaint();
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
        //f.setLayout(null);  
    }//GEN-LAST:event_jButton_VeNetDutActionPerformed

    private void jButton_NetChamGachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NetChamGachActionPerformed
        // TODO add your handling code here:
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText())*5;
            int y1 = Integer.parseInt(jTextField_y1.getText())*5;
            int x2 = Integer.parseInt(jTextField_x2.getText())*5;
            int y2 = Integer.parseInt(jTextField_y2.getText())*5;
            NetChamGach m = new NetChamGach(x1, y1, x2, y2);
//            jPanel_KhungVe.removeAll();
            jPanel_KhungVe.add(m.draw());
            jPanel_KhungVe.revalidate();
            jPanel_KhungVe.repaint();
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_NetChamGachActionPerformed

    private void jButton_NetHaiChamGachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NetHaiChamGachActionPerformed
        // TODO add your handling code here:
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText())*5;
            int y1 = Integer.parseInt(jTextField_y1.getText())*5;
            int x2 = Integer.parseInt(jTextField_x2.getText())*5;
            int y2 = Integer.parseInt(jTextField_y2.getText())*5;
            NetHaiChamGach m = new NetHaiChamGach(x1, y1, x2, y2);
//            jPanel_KhungVe.removeAll();
            jPanel_KhungVe.add(m.draw());
            jPanel_KhungVe.revalidate();
            jPanel_KhungVe.repaint();
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_NetHaiChamGachActionPerformed

    private void jButton_VeTamGiacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeTamGiacActionPerformed
        // TODO add your handling code here:
        int xDinh = Integer.parseInt(jTextField_xDinh.getText())*5;
        int yDinh = Integer.parseInt(jTextField_yDinh.getText())*5;
        int canh = Integer.parseInt(jTextField_canh.getText())*5;
        TamGiacDeu m = new TamGiacDeu(xDinh, yDinh, canh);
//        jPanel_KhungVe.removeAll();
        jPanel_KhungVe.add(m.draw());
        jPanel_KhungVe.revalidate();
        jPanel_KhungVe.repaint();
        return;
    }//GEN-LAST:event_jButton_VeTamGiacActionPerformed

    private void jButton_VeDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDiemActionPerformed
        // TODO add your handling code here:
        int x = Integer.parseInt(jTextField_x.getText())*5;
        int y = Integer.parseInt(jTextField_y.getText())*5;
        Diem m = new Diem(x, y);
//        jPanel_KhungVe.removeAll();
        jPanel_KhungVe.add(m.draw());
        jPanel_KhungVe.revalidate();
        jPanel_KhungVe.repaint();
        return;
    }//GEN-LAST:event_jButton_VeDiemActionPerformed

    private void jButton_VeMuiTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeMuiTenActionPerformed
        // TODO add your handling code here:
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText())*5;
            int y1 = Integer.parseInt(jTextField_y1.getText())*5;
            int x2 = Integer.parseInt(jTextField_x2.getText())*5;
            int y2 = Integer.parseInt(jTextField_y2.getText())*5;
            MuiTen m = new MuiTen(x1, y1, x2, y2);
//            jPanel_KhungVe.removeAll();
            jPanel_KhungVe.add(m.draw());
            jPanel_KhungVe.revalidate();
            jPanel_KhungVe.repaint();
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeMuiTenActionPerformed

    private void jButton_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_XoaActionPerformed
        // TODO add your handling code here:
        jPanel_KhungVe.removeAll();
        jPanel_KhungVe.revalidate();
        jPanel_KhungVe.repaint();
    }//GEN-LAST:event_jButton_XoaActionPerformed

    private void jButton_VeEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeEllipseActionPerformed
        // TODO add your handling code here:
        int xO = Integer.parseInt(jTextField_xC.getText())*5;
        int yO = Integer.parseInt(jTextField_yC.getText())*5;
        int a = Integer.parseInt(jTextField_a.getText())*5;
        int b = Integer.parseInt(jTextField_b.getText())*5;
        Ellipse m = new Ellipse(xO, yO, a, b);
//        jPanel_KhungVe.removeAll();
        jPanel_KhungVe.add(m.draw());
        jPanel_KhungVe.revalidate();
        jPanel_KhungVe.repaint();
        return;
    }//GEN-LAST:event_jButton_VeEllipseActionPerformed

    boolean rangBuocDuLieuDuongThang () {
        String x1 = jTextField_x1.getText();
        String y1 = jTextField_y1.getText();
        String x2 = jTextField_x2.getText();
        String y2 = jTextField_y2.getText();
        if (!x1.equals("") && !x2.equals("") && !y1.equals("") && !y2.equals("")) {
            return true;
        }
        return false;
    }
    
    boolean rangBuocDuLieuDuongTron () {
        String xO = jTextField_xO.getText();
        String yO = jTextField_yO.getText();
        String r = jTextField_r.getText();
        if (!xO.equals("") && !yO.equals("") && !r.equals("")) {
            return true;
        }
        return false;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Diem;
    private javax.swing.JPanel DoanThang;
    private javax.swing.JPanel Ellipse;
    private javax.swing.JPanel HinhTron;
    private javax.swing.JPanel TamGiacDeu;
    private javax.swing.JButton jButton_NetChamGach;
    private javax.swing.JButton jButton_NetHaiChamGach;
    private javax.swing.JButton jButton_VeDiem;
    private javax.swing.JButton jButton_VeDoanThang;
    private javax.swing.JButton jButton_VeDuongTron;
    private javax.swing.JButton jButton_VeEllipse;
    private javax.swing.JButton jButton_VeHinhChuNhat;
    private javax.swing.JButton jButton_VeMuiTen;
    private javax.swing.JButton jButton_VeNetDut;
    private javax.swing.JButton jButton_VeTamGiac;
    private javax.swing.JButton jButton_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_KhungVe;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_a;
    private javax.swing.JTextField jTextField_b;
    private javax.swing.JTextField jTextField_canh;
    private javax.swing.JTextField jTextField_r;
    private javax.swing.JTextField jTextField_x;
    private javax.swing.JTextField jTextField_x1;
    private javax.swing.JTextField jTextField_x2;
    private javax.swing.JTextField jTextField_xC;
    private javax.swing.JTextField jTextField_xDinh;
    private javax.swing.JTextField jTextField_xO;
    private javax.swing.JTextField jTextField_y;
    private javax.swing.JTextField jTextField_y1;
    private javax.swing.JTextField jTextField_y2;
    private javax.swing.JTextField jTextField_yC;
    private javax.swing.JTextField jTextField_yDinh;
    private javax.swing.JTextField jTextField_yO;
    // End of variables declaration//GEN-END:variables
}
