/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import biendoi2D.DoiXungQuaDoanThang;
import biendoi2D.Quay;
import biendoi2D.TinhTien;
import model2D.ThamSoTruyenVao;
import model2D.Diem2D;
import model2D.DoanThang;
import model2D.DuongTron;
import model2D.Ellipse;
import model2D.HinhChuNhat;
import model2D.MuiTen;
import model2D.NetChamGach;
import model2D.NetDut;
import model2D.NetHaiChamGach;
import model2D.TamGiacDeu;
import java.awt.Graphics;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model3D.HinhCau;
import model3D.HinhChop;
import model3D.HinhHop;

/**
 *
 * @author Apple Bee
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
        this.setLocationRelativeTo(null); //Hiển thị cửa sổ lên vị trí giữa màn hình
        this.setDefaultCloseOperation(EXIT_ON_CLOSE); //Thiết lập việc tắt chương trình khi click nào nút X trên thanh tiêu đề. Nếu không thêm dòng này vào thì khi bấm nút X, cửa sổ chương trình vẫn sẽ biến mất nhưng bản thân chương trình thì vẫn chạy ngầm bên dưới chứ không tắt hẳn.
        jPanel_KhungVe2D.setBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_ChuThich = new javax.swing.JLabel();
        jTabbedPane_MenuChinh = new javax.swing.JTabbedPane();
        jPanel_2D = new javax.swing.JPanel();
        jTabbedPane_Menu2D = new javax.swing.JTabbedPane();
        jPanel_Diem = new javax.swing.JPanel();
        jTextField_x = new javax.swing.JTextField();
        jTextField_y = new javax.swing.JTextField();
        jLabel_y = new javax.swing.JLabel();
        jButton_VeDiem = new javax.swing.JButton();
        jPanel_BienDoi2D = new javax.swing.JPanel();
        jButton_Quay = new javax.swing.JButton();
        jButton_TinhTien = new javax.swing.JButton();
        jButton_DoiXungQuaDuongThang = new javax.swing.JButton();
        jLabel_x = new javax.swing.JLabel();
        jPanel_DoanThang = new javax.swing.JPanel();
        jTextField_x1 = new javax.swing.JTextField();
        jLabel_x1 = new javax.swing.JLabel();
        jLabel_y1 = new javax.swing.JLabel();
        jLabel_x2 = new javax.swing.JLabel();
        jLabel_y2 = new javax.swing.JLabel();
        jTextField_y1 = new javax.swing.JTextField();
        jTextField_x2 = new javax.swing.JTextField();
        jTextField_y2 = new javax.swing.JTextField();
        jPanel_MenuDoanThang = new javax.swing.JPanel();
        jButton_VeDoanThang = new javax.swing.JButton();
        jButton_VeNetDut = new javax.swing.JButton();
        jButton_VeNetChamGach = new javax.swing.JButton();
        jButton_NetHaiChamGach = new javax.swing.JButton();
        jButton_VeMuiTen = new javax.swing.JButton();
        jButton_VeHinhChuNhat = new javax.swing.JButton();
        jPanel_TamGiacDeu = new javax.swing.JPanel();
        jTextField_xDinh = new javax.swing.JTextField();
        jLabel_xDinh = new javax.swing.JLabel();
        jLabel_yDinh = new javax.swing.JLabel();
        jTextField_yDinh = new javax.swing.JTextField();
        jLabel_Canh = new javax.swing.JLabel();
        jTextField_Canh = new javax.swing.JTextField();
        jButton_VeTamGiac = new javax.swing.JButton();
        jPanel_DuongTron = new javax.swing.JPanel();
        jLabel_xTam = new javax.swing.JLabel();
        jLabel_yTam = new javax.swing.JLabel();
        jTextField_xTam = new javax.swing.JTextField();
        jTextField_yTam = new javax.swing.JTextField();
        jButton_VeDuongTron = new javax.swing.JButton();
        jLabel_BanKinh = new javax.swing.JLabel();
        jTextField_BanKinh = new javax.swing.JTextField();
        jPanel_Ellipse = new javax.swing.JPanel();
        jLabel_Tamx = new javax.swing.JLabel();
        jTextField_Tamx = new javax.swing.JTextField();
        jLabel_Tamy = new javax.swing.JLabel();
        jTextField_Tamy = new javax.swing.JTextField();
        jTextField_BanKinhNgang = new javax.swing.JTextField();
        jLabel_BanKinhNgang = new javax.swing.JLabel();
        jButton_VeEllipse = new javax.swing.JButton();
        jLabel_BanKinhDoc = new javax.swing.JLabel();
        jTextField_BanKinhDoc = new javax.swing.JTextField();
        jPanel_KhungVe2D = new javax.swing.JPanel(){
            private static final long serialVersionUID = 1L;
            @Override
            protected void paintComponent(Graphics arg0) {
                // TODO Auto-generated method stub
                super.paintComponent(arg0);
                arg0.setColor(Color.LIGHT_GRAY);
                for (int i = 5; i< ThamSoTruyenVao.backgroundWidth; i += 5) {
                    arg0.drawLine(i,0,i,ThamSoTruyenVao.backgroundHeight);
                }
                for (int i = 5; i< ThamSoTruyenVao.backgroundHeight; i += 5) {
                    arg0.drawLine(0,i,ThamSoTruyenVao.backgroundWidth, i);
                }
                setBackground(Color.WHITE);
                arg0.setColor(Color.BLACK);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 - 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 + 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawString("O", ThamSoTruyenVao.backgroundWidth/2 + 5, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("10", ThamSoTruyenVao.backgroundWidth/2 + 50, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("20", ThamSoTruyenVao.backgroundWidth/2 + 100, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("30", ThamSoTruyenVao.backgroundWidth/2 + 150, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("40", ThamSoTruyenVao.backgroundWidth/2 + 200, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("x", ThamSoTruyenVao.backgroundWidth - 7, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("y", ThamSoTruyenVao.backgroundWidth/2 + 5, 20);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, 0, ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2);//y+
                for (int i = 1; i < ThamSoTruyenVao.backgroundWidth/100; i++) { //vach don vi
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 - 2, ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 + 2);
                }
                for (int i = 1; i < ThamSoTruyenVao.backgroundHeight/100; i++) { //vach don vi
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 2, i * 50, ThamSoTruyenVao.backgroundWidth/2 + 2, i * 50);
                }
                arg0.setColor(Color.BLUE);
                for(int i=ThamSoTruyenVao.backgroundHeight/2;i<=ThamSoTruyenVao.backgroundHeight;i+=6){//y-
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, i, ThamSoTruyenVao.backgroundWidth/2,i+3);
                }
                arg0.setColor(Color.BLACK);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);//x+
                arg0.setColor(Color.BLUE);
                for(int i=ThamSoTruyenVao.backgroundWidth/2;i>=0;i-=6){//x-
                    arg0.drawLine(i,ThamSoTruyenVao.backgroundHeight/2,i-3,ThamSoTruyenVao.backgroundHeight/2);
                }

                //        arg0.setColor(Color.BLACK);
                //        arg0.drawLine(0,BasicParam.backgroundHeight,BasicParam.backgroundWidth/2,BasicParam.backgroundHeight/2);//z+
                //        int l = BasicParam.backgroundHeight / 2;
                //        arg0.setColor(Color.BLUE);
                //        for (int i = BasicParam.backgroundWidth / 2; i <= BasicParam.backgroundWidth; i += 6) {
                    //            arg0.drawLine(i + 3, l - 3, i + 6, l - 6);
                    //            l -= 6;
                    //        }

            }
        };
        jButton_Xoa2D = new javax.swing.JButton();
        jPanel_3D = new javax.swing.JPanel();
        jPanel_KhungVe3D = new javax.swing.JPanel(){
            private static final long serialVersionUID = 1L;
            @Override
            protected void paintComponent(Graphics arg0) {
                // TODO Auto-generated method stub
                super.paintComponent(arg0);
                //        arg0.setColor(Color.LIGHT_GRAY);
                //        for (int i = 5; i< BasicParam.backgroundWidth; i += 5) {
                    //            arg0.drawLine(i,0,i,BasicParam.backgroundHeight);
                    //        }
                //        for (int i = 5; i< BasicParam.backgroundHeight; i += 5) {
                    //            arg0.drawLine(0,i,BasicParam.backgroundWidth, i);
                    //        }
                setBackground(Color.WHITE);
                arg0.setColor(Color.BLACK);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 - 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 + 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawString("O", ThamSoTruyenVao.backgroundWidth/2 + 5, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("10", ThamSoTruyenVao.backgroundWidth/2 + 50, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("20", ThamSoTruyenVao.backgroundWidth/2 + 100, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("30", ThamSoTruyenVao.backgroundWidth/2 + 150, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("40", ThamSoTruyenVao.backgroundWidth/2 + 200, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("x", ThamSoTruyenVao.backgroundWidth - 5, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("z", ThamSoTruyenVao.backgroundWidth/2 + 5, 20);
                //        arg0.drawString(">", BasicParam.backgroundWidth, BasicParam.backgroundHeight/2 + 5);
                //        arg0.drawString("/\\", BasicParam.backgroundWidth/2 - 3, 10);
                    arg0.drawString("y", 5, ThamSoTruyenVao.backgroundHeight - 20);
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, 0, ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2);//y+
                    for (int i = 1; i < ThamSoTruyenVao.backgroundWidth/100; i++) { //vach don vi
                        arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 - 2, ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 + 2);
                    }
                    for (int i = 1; i < ThamSoTruyenVao.backgroundHeight/100; i++) { //vach don vi
                        arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 2, i * 50, ThamSoTruyenVao.backgroundWidth/2 + 2, i * 50);
                    }
                    arg0.setColor(Color.BLUE);
                    for(int i=ThamSoTruyenVao.backgroundHeight/2;i<=ThamSoTruyenVao.backgroundHeight;i+=6){//y-
                        arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, i, ThamSoTruyenVao.backgroundWidth/2,i+3);
                    }
                    arg0.setColor(Color.BLACK);
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);//x+
                    arg0.setColor(Color.BLUE);
                    for(int i=ThamSoTruyenVao.backgroundWidth/2;i>=0;i-=6){//x-
                        arg0.drawLine(i,ThamSoTruyenVao.backgroundHeight/2,i-3,ThamSoTruyenVao.backgroundHeight/2);
                    }

                    arg0.setColor(Color.BLACK);
                    arg0.drawLine(0,ThamSoTruyenVao.backgroundHeight,ThamSoTruyenVao.backgroundWidth/2,ThamSoTruyenVao.backgroundHeight/2);//z+
                    int l = ThamSoTruyenVao.backgroundHeight / 2;
                    arg0.setColor(Color.BLUE);
                    for (int i = ThamSoTruyenVao.backgroundWidth / 2; i <= ThamSoTruyenVao.backgroundWidth; i += 6) {
                        arg0.drawLine(i + 3, l - 3, i + 6, l - 6);
                        l -= 6;
                    }

                }
            };
            jPanel_Menu3D = new javax.swing.JPanel();
            jButton_VeHinhHop = new javax.swing.JButton();
            jButton_VeHinhChop = new javax.swing.JButton();
            jButton_VeHinhCau = new javax.swing.JButton();
            jButton_Xoa3D = new javax.swing.JButton();
            jScrollPane_ToaDo = new javax.swing.JScrollPane();
            jTextArea_ToaDo = new javax.swing.JTextArea();
            jTextArea_ToaDo.setEditable(false);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(0, 204, 255));
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel_ChuThich.setForeground(new java.awt.Color(153, 153, 153));
            jLabel_ChuThich.setText("1 đơn vị = 5 pixel");
            getContentPane().add(jLabel_ChuThich, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            jPanel_2D.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jTabbedPane_Menu2D.setBackground(new java.awt.Color(0, 204, 255));

            jPanel_Diem.setBackground(new java.awt.Color(0, 204, 255));
            jPanel_Diem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            jPanel_Diem.add(jTextField_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 112, -1));
            jPanel_Diem.add(jTextField_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 112, -1));

            jLabel_y.setText("y:");
            jPanel_Diem.add(jLabel_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

            jButton_VeDiem.setText("Vẽ điểm");
            jButton_VeDiem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDiemActionPerformed(evt);
                }
            });
            jPanel_Diem.add(jButton_VeDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, 40));

            jPanel_BienDoi2D.setBackground(new java.awt.Color(0, 204, 255));
            jPanel_BienDoi2D.setLayout(new java.awt.GridLayout(3, 0));

            jButton_Quay.setText("Quay");
            jButton_Quay.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_QuayActionPerformed(evt);
                }
            });
            jPanel_BienDoi2D.add(jButton_Quay);

            jButton_TinhTien.setText("Tịnh tiến");
            jButton_TinhTien.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_TinhTienActionPerformed(evt);
                }
            });
            jPanel_BienDoi2D.add(jButton_TinhTien);

            jButton_DoiXungQuaDuongThang.setText("Đối xứng qua đường thẳng");
            jButton_DoiXungQuaDuongThang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_DoiXungQuaDuongThangActionPerformed(evt);
                }
            });
            jPanel_BienDoi2D.add(jButton_DoiXungQuaDuongThang);

            jPanel_Diem.add(jPanel_BienDoi2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 200, 80));

            jLabel_x.setText("x:");
            jPanel_Diem.add(jLabel_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

            jTabbedPane_Menu2D.addTab("Điểm", jPanel_Diem);

            jPanel_DoanThang.setBackground(new java.awt.Color(0, 204, 255));
            jPanel_DoanThang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            jPanel_DoanThang.add(jTextField_x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 116, -1));

            jLabel_x1.setText("x1:");
            jPanel_DoanThang.add(jLabel_x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

            jLabel_y1.setText("y1:");
            jPanel_DoanThang.add(jLabel_y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

            jLabel_x2.setText("x2:");
            jPanel_DoanThang.add(jLabel_x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

            jLabel_y2.setText("y2:");
            jPanel_DoanThang.add(jLabel_y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));
            jPanel_DoanThang.add(jTextField_y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 116, -1));
            jPanel_DoanThang.add(jTextField_x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 116, -1));
            jPanel_DoanThang.add(jTextField_y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 116, -1));

            jPanel_MenuDoanThang.setBackground(new java.awt.Color(0, 204, 255));
            jPanel_MenuDoanThang.setLayout(new java.awt.GridLayout(3, 2, 20, 20));

            jButton_VeDoanThang.setText("Vẽ đoạn thẳng");
            jButton_VeDoanThang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDoanThangActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeDoanThang);

            jButton_VeNetDut.setText("Vẽ nét đứt");
            jButton_VeNetDut.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeNetDutActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeNetDut);

            jButton_VeNetChamGach.setText("Vẽ nét chấm gạch");
            jButton_VeNetChamGach.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeNetChamGachActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeNetChamGach);

            jButton_NetHaiChamGach.setText("Vẽ nét hai chấm gạch");
            jButton_NetHaiChamGach.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_NetHaiChamGachActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_NetHaiChamGach);

            jButton_VeMuiTen.setText("Vẽ mũi tên");
            jButton_VeMuiTen.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeMuiTenActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeMuiTen);

            jButton_VeHinhChuNhat.setText("Vẽ hình chữ nhật");
            jButton_VeHinhChuNhat.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhChuNhatActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeHinhChuNhat);

            jPanel_DoanThang.add(jPanel_MenuDoanThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 360, 170));

            jTabbedPane_Menu2D.addTab("Đoạn thẳng", jPanel_DoanThang);

            jPanel_TamGiacDeu.setBackground(new java.awt.Color(0, 204, 255));
            jPanel_TamGiacDeu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            jPanel_TamGiacDeu.add(jTextField_xDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 112, -1));

            jLabel_xDinh.setText("x đỉnh:");
            jPanel_TamGiacDeu.add(jLabel_xDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

            jLabel_yDinh.setText("y đỉnh:");
            jPanel_TamGiacDeu.add(jLabel_yDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));
            jPanel_TamGiacDeu.add(jTextField_yDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 112, -1));

            jLabel_Canh.setText("Cạnh a:");
            jPanel_TamGiacDeu.add(jLabel_Canh, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));
            jPanel_TamGiacDeu.add(jTextField_Canh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 112, -1));

            jButton_VeTamGiac.setText("Vẽ tam giác");
            jButton_VeTamGiac.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeTamGiacActionPerformed(evt);
                }
            });
            jPanel_TamGiacDeu.add(jButton_VeTamGiac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, 40));

            jTabbedPane_Menu2D.addTab("Tam giác đều", jPanel_TamGiacDeu);

            jPanel_DuongTron.setBackground(new java.awt.Color(0, 204, 255));
            jPanel_DuongTron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel_xTam.setText("x tâm:");
            jPanel_DuongTron.add(jLabel_xTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

            jLabel_yTam.setText("y tâm:");
            jPanel_DuongTron.add(jLabel_yTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));
            jPanel_DuongTron.add(jTextField_xTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 112, -1));
            jPanel_DuongTron.add(jTextField_yTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 112, -1));

            jButton_VeDuongTron.setText("Vẽ đường tròn");
            jButton_VeDuongTron.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDuongTronActionPerformed(evt);
                }
            });
            jPanel_DuongTron.add(jButton_VeDuongTron, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, 30));

            jLabel_BanKinh.setText("Bán kính:");
            jPanel_DuongTron.add(jLabel_BanKinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));
            jPanel_DuongTron.add(jTextField_BanKinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 112, -1));

            jTabbedPane_Menu2D.addTab("Đường tròn", jPanel_DuongTron);

            jPanel_Ellipse.setBackground(new java.awt.Color(0, 204, 255));
            jPanel_Ellipse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel_Tamx.setText("x tâm:");
            jPanel_Ellipse.add(jLabel_Tamx, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 107, -1, -1));
            jPanel_Ellipse.add(jTextField_Tamx, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 104, 112, -1));

            jLabel_Tamy.setText("y tâm:");
            jPanel_Ellipse.add(jLabel_Tamy, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 138, -1, -1));
            jPanel_Ellipse.add(jTextField_Tamy, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 135, 112, -1));
            jPanel_Ellipse.add(jTextField_BanKinhNgang, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 166, 112, -1));

            jLabel_BanKinhNgang.setText("Bán kính ngang:");
            jPanel_Ellipse.add(jLabel_BanKinhNgang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 169, -1, -1));

            jButton_VeEllipse.setText("Vẽ Ellipse");
            jButton_VeEllipse.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeEllipseActionPerformed(evt);
                }
            });
            jPanel_Ellipse.add(jButton_VeEllipse, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 254, 120, 30));

            jLabel_BanKinhDoc.setText("Bán kính dọc:");
            jPanel_Ellipse.add(jLabel_BanKinhDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, -1, 20));
            jPanel_Ellipse.add(jTextField_BanKinhDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 197, 112, -1));

            jTabbedPane_Menu2D.addTab("Ellipse", jPanel_Ellipse);

            jPanel_2D.add(jTabbedPane_Menu2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 450));

            jPanel_KhungVe2D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout jPanel_KhungVe2DLayout = new javax.swing.GroupLayout(jPanel_KhungVe2D);
            jPanel_KhungVe2D.setLayout(jPanel_KhungVe2DLayout);
            jPanel_KhungVe2DLayout.setHorizontalGroup(
                jPanel_KhungVe2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );
            jPanel_KhungVe2DLayout.setVerticalGroup(
                jPanel_KhungVe2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );

            jPanel_2D.add(jPanel_KhungVe2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 500, -1));

            jButton_Xoa2D.setText("Xóa tất cả");
            jButton_Xoa2D.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_Xoa2DActionPerformed(evt);
                }
            });
            jPanel_2D.add(jButton_Xoa2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 470, 50));

            jTabbedPane_MenuChinh.addTab("Vẽ 2D", jPanel_2D);

            jPanel_3D.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel_KhungVe3D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout jPanel_KhungVe3DLayout = new javax.swing.GroupLayout(jPanel_KhungVe3D);
            jPanel_KhungVe3D.setLayout(jPanel_KhungVe3DLayout);
            jPanel_KhungVe3DLayout.setHorizontalGroup(
                jPanel_KhungVe3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 508, Short.MAX_VALUE)
            );
            jPanel_KhungVe3DLayout.setVerticalGroup(
                jPanel_KhungVe3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );

            jPanel_3D.add(jPanel_KhungVe3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 510, -1));

            jPanel_Menu3D.setBackground(new java.awt.Color(0, 204, 204));
            jPanel_Menu3D.setBorder(javax.swing.BorderFactory.createCompoundBorder());

            jButton_VeHinhHop.setBackground(new java.awt.Color(247, 247, 247));
            jButton_VeHinhHop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinhhop.png"))); // NOI18N
            jButton_VeHinhHop.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhHopActionPerformed(evt);
                }
            });

            jButton_VeHinhChop.setBackground(new java.awt.Color(247, 247, 247));
            jButton_VeHinhChop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinhchop.PNG"))); // NOI18N
            jButton_VeHinhChop.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhChopActionPerformed(evt);
                }
            });

            jButton_VeHinhCau.setBackground(new java.awt.Color(247, 247, 247));
            jButton_VeHinhCau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinhcau.PNG"))); // NOI18N
            jButton_VeHinhCau.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhCauActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel_Menu3DLayout = new javax.swing.GroupLayout(jPanel_Menu3D);
            jPanel_Menu3D.setLayout(jPanel_Menu3DLayout);
            jPanel_Menu3DLayout.setHorizontalGroup(
                jPanel_Menu3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_Menu3DLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jButton_VeHinhHop, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton_VeHinhChop)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton_VeHinhCau)
                    .addContainerGap(74, Short.MAX_VALUE))
            );
            jPanel_Menu3DLayout.setVerticalGroup(
                jPanel_Menu3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_Menu3DLayout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addGroup(jPanel_Menu3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_VeHinhHop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_VeHinhChop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_VeHinhCau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addContainerGap(32, Short.MAX_VALUE))
            );

            jPanel_3D.add(jPanel_Menu3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 160));

            jButton_Xoa3D.setText("Xóa tất cả");
            jButton_Xoa3D.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_Xoa3DActionPerformed(evt);
                }
            });
            jPanel_3D.add(jButton_Xoa3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 450, 460, 50));

            jTextArea_ToaDo.setBackground(new java.awt.Color(51, 51, 51));
            jTextArea_ToaDo.setColumns(20);
            jTextArea_ToaDo.setForeground(new java.awt.Color(255, 255, 255));
            jTextArea_ToaDo.setRows(5);
            jScrollPane_ToaDo.setViewportView(jTextArea_ToaDo);

            jPanel_3D.add(jScrollPane_ToaDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 460, 290));

            jTabbedPane_MenuChinh.addTab("Vẽ 3D", jPanel_3D);

            getContentPane().add(jTabbedPane_MenuChinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton_VeDoanThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDoanThangActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            DoanThang m = new DoanThang(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeDoanThangActionPerformed

    private void jButton_VeHinhChuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhChuNhatActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            HinhChuNhat m = new HinhChuNhat(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeHinhChuNhatActionPerformed

    private void jButton_VeDuongTronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDuongTronActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongTron() == true) {
            int xO = Integer.parseInt(jTextField_xTam.getText());
            int yO = Integer.parseInt(jTextField_yTam.getText());
            int r = Integer.parseInt(jTextField_BanKinh.getText());
            DuongTron m = new DuongTron(xO, yO, r);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeDuongTronActionPerformed

    private void jButton_VeNetDutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeNetDutActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            NetDut m = new NetDut(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
        //f.setLayout(null);  
    }//GEN-LAST:event_jButton_VeNetDutActionPerformed

    private void jButton_VeNetChamGachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeNetChamGachActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            NetChamGach m = new NetChamGach(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeNetChamGachActionPerformed

    private void jButton_NetHaiChamGachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NetHaiChamGachActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            NetHaiChamGach m = new NetHaiChamGach(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_NetHaiChamGachActionPerformed

    private void jButton_VeTamGiacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeTamGiacActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int xDinh = Integer.parseInt(jTextField_xDinh.getText());
        int yDinh = Integer.parseInt(jTextField_yDinh.getText());
        int canh = Integer.parseInt(jTextField_Canh.getText());
        TamGiacDeu m = new TamGiacDeu(xDinh, yDinh, canh);
        jPanel_KhungVe2D.add(m.draw());
        jPanel_KhungVe2D.repaint();
    }//GEN-LAST:event_jButton_VeTamGiacActionPerformed

    private void jButton_VeDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDiemActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        m.draw(g);
    }//GEN-LAST:event_jButton_VeDiemActionPerformed

    private void jButton_VeMuiTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeMuiTenActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            MuiTen m = new MuiTen(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeMuiTenActionPerformed

    private void jButton_Xoa2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Xoa2DActionPerformed
        jPanel_KhungVe2D.removeAll();
        jPanel_KhungVe2D.repaint();
    }//GEN-LAST:event_jButton_Xoa2DActionPerformed

    private void jButton_VeEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeEllipseActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int xO = Integer.parseInt(jTextField_Tamx.getText());
        int yO = Integer.parseInt(jTextField_Tamy.getText());
        int a = Integer.parseInt(jTextField_BanKinhNgang.getText());
        int b = Integer.parseInt(jTextField_BanKinhDoc.getText());
        Ellipse m = new Ellipse(xO, yO, a, b);
        m.draw(g);
    }//GEN-LAST:event_jButton_VeEllipseActionPerformed

    private void jButton_VeHinhHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhHopActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        HinhHop hh = new HinhHop();
        hh.nhapToaDo3D();
        ThamSoTruyenVao.nutVe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutVe.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutXoa.setBackground(Color.WHITE);
                hh.xuLyDuLieu();
                hh.draw(g);
                jTextArea_ToaDo.setText(hh.layDuLieu());
            }
        });
        ThamSoTruyenVao.nutXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutXoa.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutVe.setBackground(Color.WHITE);
                hh.xoaDuLieu();
            }
        });
    }//GEN-LAST:event_jButton_VeHinhHopActionPerformed

    private void jButton_VeHinhChopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhChopActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        HinhChop hc = new HinhChop();
        hc.nhapToaDo3D();
        ThamSoTruyenVao.nutVe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutVe.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutXoa.setBackground(Color.WHITE);
                hc.xuLyDuLieu();
                hc.draw(g);
                jTextArea_ToaDo.setText(hc.layDuLieu());
            }
        });
        ThamSoTruyenVao.nutXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutXoa.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutVe.setBackground(Color.WHITE);
                hc.xoaDuLieu();
            }
        });
    }//GEN-LAST:event_jButton_VeHinhChopActionPerformed

    private void jButton_Xoa3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Xoa3DActionPerformed
        // TODO add your handling code here:
        jPanel_KhungVe3D.repaint();
        jTextArea_ToaDo.setText("");
    }//GEN-LAST:event_jButton_Xoa3DActionPerformed

    private void jButton_TinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TinhTienActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        int dx, dy;
        dx = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập khoảng tịnh tiến dx:"));
        dy = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập khoảng tịnh tiến dy:"));
        m = TinhTien.TinhTien(m, dx, dy);
        m.draw(g);
    }//GEN-LAST:event_jButton_TinhTienActionPerformed

    private void jButton_QuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuayActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        Diem2D tam = new Diem2D();
        float gocQuay;
        tam.setX(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập hoành độ tâm:")));
        tam.setY(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập tung độ tâm:")));
        gocQuay = Float.parseFloat(JOptionPane.showInputDialog(this, "Nhập a (góc quay = a x pi (đơn vị radian)):"));
        m = Quay.QuayTamBatKy(tam, m, (Math.PI) * gocQuay);
        m.draw(g);
    }//GEN-LAST:event_jButton_QuayActionPerformed

    private void jButton_DoiXungQuaDuongThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DoiXungQuaDuongThangActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        Diem2D a = new Diem2D();
        Diem2D b = new Diem2D();
        a.setX(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập x điểm đầu")));
        a.setY(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập y điểm đầu")));
        b.setX(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập x điểm cuối")));
        b.setY(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập y điểm cuối")));
        m = DoiXungQuaDoanThang.layDoiXung(m, a, b);
        System.out.println(m.getX() + " " + m.getY());
        m.draw(g);
        DoanThang ab = new DoanThang(a.getX(), a.getY(), b.getX(), b.getY());
        ab.draw(g);
    }//GEN-LAST:event_jButton_DoiXungQuaDuongThangActionPerformed

    private void jButton_VeHinhCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhCauActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        HinhCau hc = new HinhCau();
        hc.nhapToaDo3D();
        ThamSoTruyenVao.nutVe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutVe.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutXoa.setBackground(Color.WHITE);
                hc.xuLyDuLieu();
                hc.draw(g);
                jTextArea_ToaDo.setText(hc.layDuLieu());
            }
        });
        ThamSoTruyenVao.nutXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutXoa.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutVe.setBackground(Color.WHITE);
                hc.xoaDuLieu();
            }
        });
    }//GEN-LAST:event_jButton_VeHinhCauActionPerformed

    boolean rangBuocDuLieuDuongThang() {
        String x1 = jTextField_x1.getText();
        String y1 = jTextField_y1.getText();
        String x2 = jTextField_x2.getText();
        String y2 = jTextField_y2.getText();
        if (!x1.equals("") && !x2.equals("") && !y1.equals("") && !y2.equals("")) {
            return true;
        }
        return false;
    }

    boolean rangBuocDuLieuDuongTron() {
        String xO = jTextField_xTam.getText();
        String yO = jTextField_yTam.getText();
        String r = jTextField_BanKinh.getText();
        if (!xO.equals("") && !yO.equals("") && !r.equals("")) {
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_DoiXungQuaDuongThang;
    private javax.swing.JButton jButton_NetHaiChamGach;
    private javax.swing.JButton jButton_Quay;
    private javax.swing.JButton jButton_TinhTien;
    private javax.swing.JButton jButton_VeDiem;
    private javax.swing.JButton jButton_VeDoanThang;
    private javax.swing.JButton jButton_VeDuongTron;
    private javax.swing.JButton jButton_VeEllipse;
    private javax.swing.JButton jButton_VeHinhCau;
    private javax.swing.JButton jButton_VeHinhChop;
    private javax.swing.JButton jButton_VeHinhChuNhat;
    private javax.swing.JButton jButton_VeHinhHop;
    private javax.swing.JButton jButton_VeMuiTen;
    private javax.swing.JButton jButton_VeNetChamGach;
    private javax.swing.JButton jButton_VeNetDut;
    private javax.swing.JButton jButton_VeTamGiac;
    private javax.swing.JButton jButton_Xoa2D;
    private javax.swing.JButton jButton_Xoa3D;
    private javax.swing.JLabel jLabel_BanKinh;
    private javax.swing.JLabel jLabel_BanKinhDoc;
    private javax.swing.JLabel jLabel_BanKinhNgang;
    private javax.swing.JLabel jLabel_Canh;
    private javax.swing.JLabel jLabel_ChuThich;
    private javax.swing.JLabel jLabel_Tamx;
    private javax.swing.JLabel jLabel_Tamy;
    private javax.swing.JLabel jLabel_x;
    private javax.swing.JLabel jLabel_x1;
    private javax.swing.JLabel jLabel_x2;
    private javax.swing.JLabel jLabel_xDinh;
    private javax.swing.JLabel jLabel_xTam;
    private javax.swing.JLabel jLabel_y;
    private javax.swing.JLabel jLabel_y1;
    private javax.swing.JLabel jLabel_y2;
    private javax.swing.JLabel jLabel_yDinh;
    private javax.swing.JLabel jLabel_yTam;
    private javax.swing.JPanel jPanel_2D;
    private javax.swing.JPanel jPanel_3D;
    private javax.swing.JPanel jPanel_BienDoi2D;
    private javax.swing.JPanel jPanel_Diem;
    private javax.swing.JPanel jPanel_DoanThang;
    private javax.swing.JPanel jPanel_DuongTron;
    private javax.swing.JPanel jPanel_Ellipse;
    private javax.swing.JPanel jPanel_KhungVe2D;
    private javax.swing.JPanel jPanel_KhungVe3D;
    private javax.swing.JPanel jPanel_Menu3D;
    private javax.swing.JPanel jPanel_MenuDoanThang;
    private javax.swing.JPanel jPanel_TamGiacDeu;
    private javax.swing.JScrollPane jScrollPane_ToaDo;
    private javax.swing.JTabbedPane jTabbedPane_Menu2D;
    private javax.swing.JTabbedPane jTabbedPane_MenuChinh;
    private javax.swing.JTextArea jTextArea_ToaDo;
    private javax.swing.JTextField jTextField_BanKinh;
    private javax.swing.JTextField jTextField_BanKinhDoc;
    private javax.swing.JTextField jTextField_BanKinhNgang;
    private javax.swing.JTextField jTextField_Canh;
    private javax.swing.JTextField jTextField_Tamx;
    private javax.swing.JTextField jTextField_Tamy;
    private javax.swing.JTextField jTextField_x;
    private javax.swing.JTextField jTextField_x1;
    private javax.swing.JTextField jTextField_x2;
    private javax.swing.JTextField jTextField_xDinh;
    private javax.swing.JTextField jTextField_xTam;
    private javax.swing.JTextField jTextField_y;
    private javax.swing.JTextField jTextField_y1;
    private javax.swing.JTextField jTextField_y2;
    private javax.swing.JTextField jTextField_yDinh;
    private javax.swing.JTextField jTextField_yTam;
    // End of variables declaration//GEN-END:variables
}
