/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import biendoi2D.DoiXungQuaDoanThang;
import biendoi2D.Quay;
import biendoi2D.TinhTien;
import biendoi3D.DoiXungQuaDiem;
import model2D.ThamSoTruyenVao;
import model2D.Diem2D;
import model2D.DoanThang;
import model2D.DuongTron;
import model2D.Ellipse;
import model2D.HinhChuNhat;
import model2D.MuiTen;
import model2D.NetChamGach;
import model2D.NetDut;
import model2D.NetHaiChamGach;
import model2D.TamGiacDeu;
import java.awt.Graphics;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model2Dchuyendong.ChongChong;
import model2Dchuyendong.OTo;
import model3D.Diem3D;
import model3D.HinhCau;
import model3D.HinhChop;
import model3D.HinhHop;

/**
 *
 * @author Apple Bee
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public Diem3D A = new Diem3D();

    public GiaoDienChinh() {
        initComponents();
        this.setLocationRelativeTo(null); //Hiển thị cửa sổ lên vị trí giữa màn hình
        this.setDefaultCloseOperation(EXIT_ON_CLOSE); //Thiết lập việc tắt chương trình khi click nào nút X trên thanh tiêu đề. Nếu không thêm dòng này vào thì khi bấm nút X, cửa sổ chương trình vẫn sẽ biến mất nhưng bản thân chương trình thì vẫn chạy ngầm bên dưới chứ không tắt hẳn.
        System.out.println(jPanel_KhungVe2DChuyenDong.getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup_Vat2DChuyenDong = new javax.swing.ButtonGroup();
        jTabbedPane_MenuChinh = new javax.swing.JTabbedPane();
        jPanel_2D = new javax.swing.JPanel();
        jTabbedPane_Menu2D = new javax.swing.JTabbedPane();
        jPanel_DoanThang = new javax.swing.JPanel();
        jTextField_x1 = new javax.swing.JTextField();
        jTextField_y1 = new javax.swing.JTextField();
        jTextField_x2 = new javax.swing.JTextField();
        jTextField_y2 = new javax.swing.JTextField();
        jPanel_MenuDoanThang = new javax.swing.JPanel();
        jButton_VeDoanThang = new javax.swing.JButton();
        jButton_VeNetDut = new javax.swing.JButton();
        jButton_VeNetChamGach = new javax.swing.JButton();
        jButton_NetHaiChamGach = new javax.swing.JButton();
        jButton_VeMuiTen = new javax.swing.JButton();
        jButton_VeHinhChuNhat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_TamGiacDeu = new javax.swing.JPanel();
        jTextField_xDinh = new javax.swing.JTextField();
        jLabel_xDinh = new javax.swing.JLabel();
        jLabel_yDinh = new javax.swing.JLabel();
        jTextField_yDinh = new javax.swing.JTextField();
        jLabel_Canh = new javax.swing.JLabel();
        jTextField_Canh = new javax.swing.JTextField();
        jButton_VeTamGiac = new javax.swing.JButton();
        jPanel_DuongTron = new javax.swing.JPanel();
        jLabel_xTam = new javax.swing.JLabel();
        jLabel_yTam = new javax.swing.JLabel();
        jTextField_xTam = new javax.swing.JTextField();
        jTextField_yTam = new javax.swing.JTextField();
        jButton_VeDuongTron = new javax.swing.JButton();
        jLabel_BanKinh = new javax.swing.JLabel();
        jTextField_BanKinh = new javax.swing.JTextField();
        jPanel_Diem = new javax.swing.JPanel();
        jTextField_x = new javax.swing.JTextField();
        jTextField_y = new javax.swing.JTextField();
        jLabel_y = new javax.swing.JLabel();
        jButton_VeDiem = new javax.swing.JButton();
        jPanel_BienDoi2D = new javax.swing.JPanel();
        jButton_TinhTien = new javax.swing.JButton();
        jButton_Quay = new javax.swing.JButton();
        jButton_DoiXungQuaDuongThang = new javax.swing.JButton();
        jLabel_x = new javax.swing.JLabel();
        jPanel_Ellipse = new javax.swing.JPanel();
        jLabel_Tamx = new javax.swing.JLabel();
        jTextField_Tamx = new javax.swing.JTextField();
        jLabel_Tamy = new javax.swing.JLabel();
        jTextField_Tamy = new javax.swing.JTextField();
        jTextField_BanKinhNgang = new javax.swing.JTextField();
        jLabel_BanKinhNgang = new javax.swing.JLabel();
        jButton_VeEllipse = new javax.swing.JButton();
        jLabel_BanKinhDoc = new javax.swing.JLabel();
        jTextField_BanKinhDoc = new javax.swing.JTextField();
        jPanel_KhungVe2D = new javax.swing.JPanel(){
            private static final long serialVersionUID = 1L;
            @Override
            protected void paintComponent(Graphics arg0) {
                // TODO Auto-generated method stub
                super.paintComponent(arg0);
                arg0.setColor(Color.LIGHT_GRAY);
                for (int i = 5; i< ThamSoTruyenVao.backgroundWidth; i += 5) {
                    arg0.drawLine(i,0,i,ThamSoTruyenVao.backgroundHeight);
                }
                for (int i = 5; i< ThamSoTruyenVao.backgroundHeight; i += 5) {
                    arg0.drawLine(0,i,ThamSoTruyenVao.backgroundWidth, i);
                }
                setBackground(Color.WHITE);
                arg0.setColor(Color.BLACK);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 - 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 + 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawString("O", ThamSoTruyenVao.backgroundWidth/2 + 5, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("10", ThamSoTruyenVao.backgroundWidth/2 + 50, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("20", ThamSoTruyenVao.backgroundWidth/2 + 100, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("30", ThamSoTruyenVao.backgroundWidth/2 + 150, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("40", ThamSoTruyenVao.backgroundWidth/2 + 200, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("x", ThamSoTruyenVao.backgroundWidth - 7, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("y", ThamSoTruyenVao.backgroundWidth/2 + 5, 20);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, 0, ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2);//y+
                for (int i = 1; i < ThamSoTruyenVao.backgroundWidth/100; i++) { //vach don vi
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 - 2, ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 + 2);
                }
                for (int i = 1; i < ThamSoTruyenVao.backgroundHeight/100; i++) { //vach don vi
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 2, i * 50, ThamSoTruyenVao.backgroundWidth/2 + 2, i * 50);
                }
                arg0.setColor(Color.BLUE);
                for(int i=ThamSoTruyenVao.backgroundHeight/2;i<=ThamSoTruyenVao.backgroundHeight;i+=6){//y-
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, i, ThamSoTruyenVao.backgroundWidth/2,i+3);
                }
                arg0.setColor(Color.BLACK);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);//x+
                arg0.setColor(Color.BLUE);
                for(int i=ThamSoTruyenVao.backgroundWidth/2;i>=0;i-=6){//x-
                    arg0.drawLine(i,ThamSoTruyenVao.backgroundHeight/2,i-3,ThamSoTruyenVao.backgroundHeight/2);
                }

                //        arg0.setColor(Color.BLACK);
                //        arg0.drawLine(0,BasicParam.backgroundHeight,BasicParam.backgroundWidth/2,BasicParam.backgroundHeight/2);//z+
                //        int l = BasicParam.backgroundHeight / 2;
                //        arg0.setColor(Color.BLUE);
                //        for (int i = BasicParam.backgroundWidth / 2; i <= BasicParam.backgroundWidth; i += 6) {
                    //            arg0.drawLine(i + 3, l - 3, i + 6, l - 6);
                    //            l -= 6;
                    //        }

            }
        };
        jButton_Xoa2D = new javax.swing.JButton();
        jPanel_3D = new javax.swing.JPanel();
        jPanel_KhungVe3D = new javax.swing.JPanel(){
            private static final long serialVersionUID = 1L;
            @Override
            protected void paintComponent(Graphics arg0) {
                // TODO Auto-generated method stub
                super.paintComponent(arg0);
                //        arg0.setColor(Color.LIGHT_GRAY);
                //        for (int i = 5; i< BasicParam.backgroundWidth; i += 5) {
                    //            arg0.drawLine(i,0,i,BasicParam.backgroundHeight);
                    //        }
                //        for (int i = 5; i< BasicParam.backgroundHeight; i += 5) {
                    //            arg0.drawLine(0,i,BasicParam.backgroundWidth, i);
                    //        }
                setBackground(Color.WHITE);
                arg0.setColor(Color.BLACK);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 - 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 + 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawString("O", ThamSoTruyenVao.backgroundWidth/2 + 5, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("10", ThamSoTruyenVao.backgroundWidth/2 + 50, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("20", ThamSoTruyenVao.backgroundWidth/2 + 100, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("30", ThamSoTruyenVao.backgroundWidth/2 + 150, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("40", ThamSoTruyenVao.backgroundWidth/2 + 200, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("x", ThamSoTruyenVao.backgroundWidth - 5, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("z", ThamSoTruyenVao.backgroundWidth/2 + 5, 20);
                //        arg0.drawString(">", BasicParam.backgroundWidth, BasicParam.backgroundHeight/2 + 5);
                //        arg0.drawString("/\\", BasicParam.backgroundWidth/2 - 3, 10);
                    arg0.drawString("y", 5, ThamSoTruyenVao.backgroundHeight - 20);
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, 0, ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2);//y+
                    for (int i = 1; i < ThamSoTruyenVao.backgroundWidth/100; i++) { //vach don vi
                        arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 - 2, ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 + 2);
                    }
                    for (int i = 1; i < ThamSoTruyenVao.backgroundHeight/100; i++) { //vach don vi
                        arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 2, i * 50, ThamSoTruyenVao.backgroundWidth/2 + 2, i * 50);
                    }
                    arg0.setColor(Color.BLUE);
                    for(int i=ThamSoTruyenVao.backgroundHeight/2;i<=ThamSoTruyenVao.backgroundHeight;i+=6){//y-
                        arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, i, ThamSoTruyenVao.backgroundWidth/2,i+3);
                    }
                    arg0.setColor(Color.BLACK);
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);//x+
                    arg0.setColor(Color.BLUE);
                    for(int i=ThamSoTruyenVao.backgroundWidth/2;i>=0;i-=6){//x-
                        arg0.drawLine(i,ThamSoTruyenVao.backgroundHeight/2,i-3,ThamSoTruyenVao.backgroundHeight/2);
                    }

                    arg0.setColor(Color.BLACK);
                    arg0.drawLine(0,ThamSoTruyenVao.backgroundHeight,ThamSoTruyenVao.backgroundWidth/2,ThamSoTruyenVao.backgroundHeight/2);//z+
                    int l = ThamSoTruyenVao.backgroundHeight / 2;
                    arg0.setColor(Color.BLUE);
                    for (int i = ThamSoTruyenVao.backgroundWidth / 2; i <= ThamSoTruyenVao.backgroundWidth; i += 6) {
                        arg0.drawLine(i + 3, l - 3, i + 6, l - 6);
                        l -= 6;
                    }

                }
            };
            jPanel_Menu3D = new javax.swing.JPanel();
            jButton_VeHinhHop = new javax.swing.JButton();
            jButton_VeHinhChop = new javax.swing.JButton();
            jButton_VeHinhCau = new javax.swing.JButton();
            jButton_VeDiem3D = new javax.swing.JButton();
            jButton_ĐoiXungQuaDiem = new javax.swing.JButton();
            jButton_Xoa3D = new javax.swing.JButton();
            jScrollPane_ToaDo = new javax.swing.JScrollPane();
            jTextArea_ToaDo = new javax.swing.JTextArea();
            jTextArea_ToaDo.setEditable(false);
            jPanel_2DChuyenDong = new javax.swing.JPanel();
            jPanel_KhungVe2DChuyenDong = new javax.swing.JPanel(){
                private static final long serialVersionUID = 1L;
                @Override
                protected void paintComponent(Graphics arg0) {
                    // TODO Auto-generated method stub
                    super.paintComponent(arg0);
                    arg0.setColor(Color.LIGHT_GRAY);
                    for (int i = 5; i< 700; i += 5) {
                        arg0.drawLine(i,0,i,ThamSoTruyenVao.backgroundHeight);
                    }
                    for (int i = 5; i< ThamSoTruyenVao.backgroundHeight; i += 5) {
                        arg0.drawLine(0,i,700, i);
                    }
                    setBackground(Color.WHITE);
                    arg0.setColor(Color.red);
                    arg0.drawLine(700/2, 0, 700/2, ThamSoTruyenVao.backgroundHeight);//y
                    arg0.drawLine(0, ThamSoTruyenVao.backgroundHeight/2, 700, ThamSoTruyenVao.backgroundHeight/2);//x
                }
            };
            jPanel_Menu2DChuyenDong = new javax.swing.JPanel() {
                public void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    ImageIcon img = new ImageIcon("src\\icon\\2.jpg");
                    g.drawImage(img.getImage(), 0, 0, jPanel_Menu2DChuyenDong);
                }
            };
            jRadioButton_ChongChong = new javax.swing.JRadioButton();
            jRadioButton_OTo = new javax.swing.JRadioButton();
            jPanel_ChucNang2DChuyenDong = new javax.swing.JPanel();
            jButton_2DTinhTien = new javax.swing.JButton();
            jButton_2Quay = new javax.swing.JButton();
            jButton_2DDoiXung = new javax.swing.JButton();
            jButton_2DThuPhong = new javax.swing.JButton();
            jButton_2DVe = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTextArea_ToaDoVat = new javax.swing.JTextArea();
            jPane_HoatCanh = new javax.swing.JPanel();
            jPanel_KhungVeHoatCanh = new javax.swing.JPanel(){
                private static final long serialVersionUID = 1L;
                @Override
                protected void paintComponent(Graphics arg0) {
                    // TODO Auto-generated method stub
                    super.paintComponent(arg0);
                    arg0.setColor(Color.LIGHT_GRAY);
                    for (int i = 5; i< 700; i += 5) {
                        arg0.drawLine(i,0,i,ThamSoTruyenVao.backgroundHeight);
                    }
                    for (int i = 5; i< ThamSoTruyenVao.backgroundHeight; i += 5) {
                        arg0.drawLine(0,i,700, i);
                    }
                    setBackground(Color.WHITE);
                    arg0.setColor(Color.red);
                    arg0.drawLine(700/2, 0, 700/2, ThamSoTruyenVao.backgroundHeight);//y
                    arg0.drawLine(0, ThamSoTruyenVao.backgroundHeight/2, 700, ThamSoTruyenVao.backgroundHeight/2);//x
                }
            };
            jButton_Run = new javax.swing.JButton();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(0, 204, 255));
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jTabbedPane_MenuChinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

            jPanel_2D.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jTabbedPane_Menu2D.setBackground(new java.awt.Color(102, 204, 255));
            jTabbedPane_Menu2D.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

            jPanel_DoanThang.setBackground(new java.awt.Color(153, 204, 255));
            jPanel_DoanThang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jTextField_x1.setBackground(new java.awt.Color(240, 240, 240));
            jTextField_x1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(102, 204, 255)));
            jPanel_DoanThang.add(jTextField_x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 130, 30));

            jTextField_y1.setBackground(new java.awt.Color(240, 240, 240));
            jTextField_y1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(102, 204, 255)));
            jPanel_DoanThang.add(jTextField_y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 130, 30));

            jTextField_x2.setBackground(new java.awt.Color(240, 240, 240));
            jTextField_x2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(102, 204, 255)));
            jPanel_DoanThang.add(jTextField_x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 130, 30));

            jTextField_y2.setBackground(new java.awt.Color(240, 240, 240));
            jTextField_y2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(102, 204, 255)));
            jPanel_DoanThang.add(jTextField_y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 130, 30));

            jPanel_MenuDoanThang.setBackground(new java.awt.Color(153, 204, 255));
            jPanel_MenuDoanThang.setLayout(new java.awt.GridLayout(3, 2, 20, 20));

            jButton_VeDoanThang.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeDoanThang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeDoanThang.setText("Vẽ đoạn thẳng");
            jButton_VeDoanThang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDoanThangActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeDoanThang);

            jButton_VeNetDut.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeNetDut.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeNetDut.setText("Vẽ nét đứt");
            jButton_VeNetDut.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeNetDutActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeNetDut);

            jButton_VeNetChamGach.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeNetChamGach.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeNetChamGach.setText("Vẽ nét chấm gạch");
            jButton_VeNetChamGach.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeNetChamGachActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeNetChamGach);

            jButton_NetHaiChamGach.setBackground(new java.awt.Color(51, 204, 255));
            jButton_NetHaiChamGach.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_NetHaiChamGach.setText("Vẽ nét hai chấm gạch");
            jButton_NetHaiChamGach.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_NetHaiChamGachActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_NetHaiChamGach);

            jButton_VeMuiTen.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeMuiTen.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeMuiTen.setText("Vẽ mũi tên");
            jButton_VeMuiTen.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeMuiTenActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeMuiTen);

            jButton_VeHinhChuNhat.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeHinhChuNhat.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeHinhChuNhat.setText("Vẽ hình chữ nhật");
            jButton_VeHinhChuNhat.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhChuNhatActionPerformed(evt);
                }
            });
            jPanel_MenuDoanThang.add(jButton_VeHinhChuNhat);

            jPanel_DoanThang.add(jPanel_MenuDoanThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 410, 170));

            jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel1.setText("x2: ");
            jPanel_DoanThang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel2.setText("y2: ");
            jPanel_DoanThang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

            jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel3.setText("x1: ");
            jPanel_DoanThang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

            jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel4.setText("y1: ");
            jPanel_DoanThang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

            jTabbedPane_Menu2D.addTab("Đoạn thẳng", jPanel_DoanThang);

            jPanel_TamGiacDeu.setBackground(new java.awt.Color(153, 204, 255));
            jPanel_TamGiacDeu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jTextField_xDinh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 153, 255), new java.awt.Color(51, 204, 255)));
            jPanel_TamGiacDeu.add(jTextField_xDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 112, 30));

            jLabel_xDinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_xDinh.setText("x đỉnh:");
            jPanel_TamGiacDeu.add(jLabel_xDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

            jLabel_yDinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_yDinh.setText("y đỉnh:");
            jPanel_TamGiacDeu.add(jLabel_yDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

            jTextField_yDinh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 153, 255), new java.awt.Color(51, 204, 255)));
            jPanel_TamGiacDeu.add(jTextField_yDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 112, 30));

            jLabel_Canh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_Canh.setText("Cạnh a:");
            jPanel_TamGiacDeu.add(jLabel_Canh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

            jTextField_Canh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(102, 153, 255), new java.awt.Color(51, 204, 255)));
            jPanel_TamGiacDeu.add(jTextField_Canh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 112, 30));

            jButton_VeTamGiac.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeTamGiac.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeTamGiac.setText("Vẽ tam giác");
            jButton_VeTamGiac.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeTamGiacActionPerformed(evt);
                }
            });
            jPanel_TamGiacDeu.add(jButton_VeTamGiac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, 50));

            jTabbedPane_Menu2D.addTab("Tam giác đều", jPanel_TamGiacDeu);

            jPanel_DuongTron.setBackground(new java.awt.Color(153, 204, 255));
            jPanel_DuongTron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel_xTam.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_xTam.setText("x tâm:");
            jPanel_DuongTron.add(jLabel_xTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

            jLabel_yTam.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_yTam.setText("y tâm:");
            jPanel_DuongTron.add(jLabel_yTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

            jTextField_xTam.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(0, 204, 255)));
            jPanel_DuongTron.add(jTextField_xTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 112, 30));

            jTextField_yTam.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(0, 204, 255)));
            jPanel_DuongTron.add(jTextField_yTam, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 112, 30));

            jButton_VeDuongTron.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeDuongTron.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeDuongTron.setText("Vẽ đường tròn");
            jButton_VeDuongTron.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDuongTronActionPerformed(evt);
                }
            });
            jPanel_DuongTron.add(jButton_VeDuongTron, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 150, 50));

            jLabel_BanKinh.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_BanKinh.setText("Bán kính:");
            jPanel_DuongTron.add(jLabel_BanKinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

            jTextField_BanKinh.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 153, 255), new java.awt.Color(0, 204, 255)));
            jPanel_DuongTron.add(jTextField_BanKinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 112, 30));

            jTabbedPane_Menu2D.addTab("Đường tròn", jPanel_DuongTron);

            jPanel_Diem.setBackground(new java.awt.Color(153, 204, 255));
            jPanel_Diem.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
            jPanel_Diem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jTextField_x.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(0, 204, 255)));
            jPanel_Diem.add(jTextField_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 112, 30));

            jTextField_y.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(0, 204, 255)));
            jPanel_Diem.add(jTextField_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 112, 30));

            jLabel_y.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_y.setText("y:");
            jPanel_Diem.add(jLabel_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

            jButton_VeDiem.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeDiem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeDiem.setText("Vẽ điểm");
            jButton_VeDiem.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(153, 204, 255)));
            jButton_VeDiem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDiemActionPerformed(evt);
                }
            });
            jPanel_Diem.add(jButton_VeDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 110, 50));

            jPanel_BienDoi2D.setBackground(new java.awt.Color(153, 204, 255));
            jPanel_BienDoi2D.setLayout(new java.awt.GridLayout(3, 0));

            jButton_TinhTien.setBackground(new java.awt.Color(51, 204, 255));
            jButton_TinhTien.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_TinhTien.setText("Tịnh tiến");
            jButton_TinhTien.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(153, 204, 255)));
            jButton_TinhTien.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_TinhTienActionPerformed(evt);
                }
            });
            jPanel_BienDoi2D.add(jButton_TinhTien);

            jButton_Quay.setBackground(new java.awt.Color(51, 204, 255));
            jButton_Quay.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_Quay.setText("Quay");
            jButton_Quay.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(153, 204, 255)));
            jButton_Quay.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_QuayActionPerformed(evt);
                }
            });
            jPanel_BienDoi2D.add(jButton_Quay);

            jButton_DoiXungQuaDuongThang.setBackground(new java.awt.Color(51, 204, 255));
            jButton_DoiXungQuaDuongThang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_DoiXungQuaDuongThang.setText("Đối xứng qua đường thẳng");
            jButton_DoiXungQuaDuongThang.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 255), new java.awt.Color(153, 204, 255)));
            jButton_DoiXungQuaDuongThang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_DoiXungQuaDuongThangActionPerformed(evt);
                }
            });
            jPanel_BienDoi2D.add(jButton_DoiXungQuaDuongThang);

            jPanel_Diem.add(jPanel_BienDoi2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 240, 120));

            jLabel_x.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_x.setText("x:");
            jPanel_Diem.add(jLabel_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, -1, -1));

            jTabbedPane_Menu2D.addTab("Điểm", jPanel_Diem);

            jPanel_Ellipse.setBackground(new java.awt.Color(153, 204, 255));
            jPanel_Ellipse.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel_Tamx.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_Tamx.setText("x tâm:");
            jPanel_Ellipse.add(jLabel_Tamx, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

            jTextField_Tamx.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
            jPanel_Ellipse.add(jTextField_Tamx, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 130, 30));

            jLabel_Tamy.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_Tamy.setText("y tâm:");
            jPanel_Ellipse.add(jLabel_Tamy, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

            jTextField_Tamy.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
            jPanel_Ellipse.add(jTextField_Tamy, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, 30));

            jTextField_BanKinhNgang.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
            jPanel_Ellipse.add(jTextField_BanKinhNgang, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 130, 30));

            jLabel_BanKinhNgang.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_BanKinhNgang.setText("Bán kính ngang:");
            jPanel_Ellipse.add(jLabel_BanKinhNgang, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

            jButton_VeEllipse.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeEllipse.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeEllipse.setText("Vẽ Ellipse");
            jButton_VeEllipse.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeEllipseActionPerformed(evt);
                }
            });
            jPanel_Ellipse.add(jButton_VeEllipse, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, 40));

            jLabel_BanKinhDoc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jLabel_BanKinhDoc.setText("Bán kính dọc:");
            jPanel_Ellipse.add(jLabel_BanKinhDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, -1, 20));

            jTextField_BanKinhDoc.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(51, 204, 255)));
            jPanel_Ellipse.add(jTextField_BanKinhDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 130, 30));

            jTabbedPane_Menu2D.addTab("Ellipse", jPanel_Ellipse);

            jPanel_2D.add(jTabbedPane_Menu2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 450));

            jPanel_KhungVe2D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout jPanel_KhungVe2DLayout = new javax.swing.GroupLayout(jPanel_KhungVe2D);
            jPanel_KhungVe2D.setLayout(jPanel_KhungVe2DLayout);
            jPanel_KhungVe2DLayout.setHorizontalGroup(
                jPanel_KhungVe2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );
            jPanel_KhungVe2DLayout.setVerticalGroup(
                jPanel_KhungVe2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );

            jPanel_2D.add(jPanel_KhungVe2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 500, -1));

            jButton_Xoa2D.setBackground(new java.awt.Color(204, 204, 204));
            jButton_Xoa2D.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_Xoa2D.setText("Xóa tất cả");
            jButton_Xoa2D.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_Xoa2DActionPerformed(evt);
                }
            });
            jPanel_2D.add(jButton_Xoa2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 470, 50));

            jTabbedPane_MenuChinh.addTab("Vẽ 2D", jPanel_2D);

            jPanel_3D.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel_KhungVe3D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout jPanel_KhungVe3DLayout = new javax.swing.GroupLayout(jPanel_KhungVe3D);
            jPanel_KhungVe3D.setLayout(jPanel_KhungVe3DLayout);
            jPanel_KhungVe3DLayout.setHorizontalGroup(
                jPanel_KhungVe3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 508, Short.MAX_VALUE)
            );
            jPanel_KhungVe3DLayout.setVerticalGroup(
                jPanel_KhungVe3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );

            jPanel_3D.add(jPanel_KhungVe3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 510, -1));

            jPanel_Menu3D.setBackground(new java.awt.Color(0, 204, 204));
            jPanel_Menu3D.setBorder(javax.swing.BorderFactory.createCompoundBorder());

            jButton_VeHinhHop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinhhop.png"))); // NOI18N
            jButton_VeHinhHop.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhHopActionPerformed(evt);
                }
            });

            jButton_VeHinhChop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinhchop.PNG"))); // NOI18N
            jButton_VeHinhChop.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhChopActionPerformed(evt);
                }
            });

            jButton_VeHinhCau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinhcau.PNG"))); // NOI18N
            jButton_VeHinhCau.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhCauActionPerformed(evt);
                }
            });

            jButton_VeDiem3D.setBackground(new java.awt.Color(51, 204, 255));
            jButton_VeDiem3D.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_VeDiem3D.setText("Vẽ điểm");
            jButton_VeDiem3D.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(0, 153, 255)));
            jButton_VeDiem3D.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDiem3DActionPerformed(evt);
                }
            });

            jButton_ĐoiXungQuaDiem.setBackground(new java.awt.Color(51, 204, 255));
            jButton_ĐoiXungQuaDiem.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_ĐoiXungQuaDiem.setText("Đối xứng qua điểm");
            jButton_ĐoiXungQuaDiem.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 204, 255), new java.awt.Color(0, 153, 255)));
            jButton_ĐoiXungQuaDiem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_ĐoiXungQuaDiemActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel_Menu3DLayout = new javax.swing.GroupLayout(jPanel_Menu3D);
            jPanel_Menu3D.setLayout(jPanel_Menu3DLayout);
            jPanel_Menu3DLayout.setHorizontalGroup(
                jPanel_Menu3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_Menu3DLayout.createSequentialGroup()
                    .addGroup(jPanel_Menu3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel_Menu3DLayout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addComponent(jButton_VeHinhHop, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_VeHinhChop)
                            .addGap(18, 18, 18)
                            .addComponent(jButton_VeHinhCau))
                        .addGroup(jPanel_Menu3DLayout.createSequentialGroup()
                            .addGap(83, 83, 83)
                            .addComponent(jButton_VeDiem3D, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jButton_ĐoiXungQuaDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(46, Short.MAX_VALUE))
            );
            jPanel_Menu3DLayout.setVerticalGroup(
                jPanel_Menu3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_Menu3DLayout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel_Menu3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_VeHinhCau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_VeHinhChop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_VeHinhHop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel_Menu3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton_ĐoiXungQuaDiem, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(jButton_VeDiem3D, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap())
            );

            jPanel_3D.add(jPanel_Menu3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 180));

            jButton_Xoa3D.setBackground(new java.awt.Color(153, 204, 255));
            jButton_Xoa3D.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
            jButton_Xoa3D.setText("Xóa tất cả");
            jButton_Xoa3D.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_Xoa3DActionPerformed(evt);
                }
            });
            jPanel_3D.add(jButton_Xoa3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 450, 460, 50));

            jTextArea_ToaDo.setBackground(new java.awt.Color(102, 102, 102));
            jTextArea_ToaDo.setColumns(20);
            jTextArea_ToaDo.setForeground(new java.awt.Color(255, 255, 255));
            jTextArea_ToaDo.setRows(5);
            jScrollPane_ToaDo.setViewportView(jTextArea_ToaDo);

            jPanel_3D.add(jScrollPane_ToaDo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 460, 270));

            jTabbedPane_MenuChinh.addTab("Vẽ 3D", jPanel_3D);

            jPanel_KhungVe2DChuyenDong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel_KhungVe2DChuyenDong.setMinimumSize(new java.awt.Dimension(700, 500));
            jPanel_KhungVe2DChuyenDong.setPreferredSize(new java.awt.Dimension(700, 500));

            javax.swing.GroupLayout jPanel_KhungVe2DChuyenDongLayout = new javax.swing.GroupLayout(jPanel_KhungVe2DChuyenDong);
            jPanel_KhungVe2DChuyenDong.setLayout(jPanel_KhungVe2DChuyenDongLayout);
            jPanel_KhungVe2DChuyenDongLayout.setHorizontalGroup(
                jPanel_KhungVe2DChuyenDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );
            jPanel_KhungVe2DChuyenDongLayout.setVerticalGroup(
                jPanel_KhungVe2DChuyenDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 0, Short.MAX_VALUE)
            );

            jPanel_Menu2DChuyenDong.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "2D", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

            jRadioButton_ChongChong.setBackground(new java.awt.Color(0, 102, 204));
            buttonGroup_Vat2DChuyenDong.add(jRadioButton_ChongChong);
            jRadioButton_ChongChong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jRadioButton_ChongChong.setForeground(new java.awt.Color(255, 255, 255));
            jRadioButton_ChongChong.setSelected(true);
            jRadioButton_ChongChong.setText("Chong chóng");

            jRadioButton_OTo.setBackground(new java.awt.Color(0, 102, 204));
            buttonGroup_Vat2DChuyenDong.add(jRadioButton_OTo);
            jRadioButton_OTo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jRadioButton_OTo.setForeground(new java.awt.Color(255, 255, 255));
            jRadioButton_OTo.setText("Ô tô");

            jPanel_ChucNang2DChuyenDong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            jPanel_ChucNang2DChuyenDong.setBackground(new Color(0, 0, 0, 65));

            jButton_2DTinhTien.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jButton_2DTinhTien.setText("Tịnh tiến");
            jButton_2DTinhTien.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_2DTinhTienActionPerformed(evt);
                }
            });
            jPanel_ChucNang2DChuyenDong.add(jButton_2DTinhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 40));

            jButton_2Quay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jButton_2Quay.setText("Quay");
            jButton_2Quay.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_2QuayActionPerformed(evt);
                }
            });
            jPanel_ChucNang2DChuyenDong.add(jButton_2Quay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 100, 40));

            jButton_2DDoiXung.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jButton_2DDoiXung.setText("Đối xứng");
            jButton_2DDoiXung.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_2DDoiXungActionPerformed(evt);
                }
            });
            jPanel_ChucNang2DChuyenDong.add(jButton_2DDoiXung, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 40));

            jButton_2DThuPhong.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
            jButton_2DThuPhong.setText("Thu phóng");
            jButton_2DThuPhong.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_2DThuPhongActionPerformed(evt);
                }
            });
            jPanel_ChucNang2DChuyenDong.add(jButton_2DThuPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 100, 40));

            jButton_2DVe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
            jButton_2DVe.setText("Vẽ");
            jButton_2DVe.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_2DVeActionPerformed(evt);
                }
            });

            jTextArea_ToaDoVat.setEditable(false);
            jTextArea_ToaDoVat.setBackground(new java.awt.Color(0, 0, 0));
            jTextArea_ToaDoVat.setColumns(20);
            jTextArea_ToaDoVat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jTextArea_ToaDoVat.setForeground(new java.awt.Color(255, 255, 255));
            jTextArea_ToaDoVat.setRows(5);
            jScrollPane1.setViewportView(jTextArea_ToaDoVat);

            javax.swing.GroupLayout jPanel_Menu2DChuyenDongLayout = new javax.swing.GroupLayout(jPanel_Menu2DChuyenDong);
            jPanel_Menu2DChuyenDong.setLayout(jPanel_Menu2DChuyenDongLayout);
            jPanel_Menu2DChuyenDongLayout.setHorizontalGroup(
                jPanel_Menu2DChuyenDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_Menu2DChuyenDongLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jRadioButton_ChongChong)
                    .addGap(18, 18, 18)
                    .addComponent(jRadioButton_OTo)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton_2DVe)
                    .addContainerGap(22, Short.MAX_VALUE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Menu2DChuyenDongLayout.createSequentialGroup()
                    .addComponent(jPanel_ChucNang2DChuyenDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap())
                .addComponent(jScrollPane1)
            );
            jPanel_Menu2DChuyenDongLayout.setVerticalGroup(
                jPanel_Menu2DChuyenDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_Menu2DChuyenDongLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel_Menu2DChuyenDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton_ChongChong)
                        .addComponent(jRadioButton_OTo)
                        .addComponent(jButton_2DVe))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel_ChucNang2DChuyenDong, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(44, 44, 44))
            );

            javax.swing.GroupLayout jPanel_2DChuyenDongLayout = new javax.swing.GroupLayout(jPanel_2DChuyenDong);
            jPanel_2DChuyenDong.setLayout(jPanel_2DChuyenDongLayout);
            jPanel_2DChuyenDongLayout.setHorizontalGroup(
                jPanel_2DChuyenDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_2DChuyenDongLayout.createSequentialGroup()
                    .addComponent(jPanel_KhungVe2DChuyenDong, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel_Menu2DChuyenDong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE))
            );
            jPanel_2DChuyenDongLayout.setVerticalGroup(
                jPanel_2DChuyenDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_2DChuyenDongLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel_2DChuyenDongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel_Menu2DChuyenDong, javax.swing.GroupLayout.PREFERRED_SIZE, 500, Short.MAX_VALUE)
                        .addComponent(jPanel_KhungVe2DChuyenDong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(41, 41, 41))
            );

            jTabbedPane_MenuChinh.addTab("Vẽ vật", jPanel_2DChuyenDong);

            jPanel_KhungVeHoatCanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            jPanel_KhungVeHoatCanh.setMinimumSize(new java.awt.Dimension(700, 500));

            javax.swing.GroupLayout jPanel_KhungVeHoatCanhLayout = new javax.swing.GroupLayout(jPanel_KhungVeHoatCanh);
            jPanel_KhungVeHoatCanh.setLayout(jPanel_KhungVeHoatCanhLayout);
            jPanel_KhungVeHoatCanhLayout.setHorizontalGroup(
                jPanel_KhungVeHoatCanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 698, Short.MAX_VALUE)
            );
            jPanel_KhungVeHoatCanhLayout.setVerticalGroup(
                jPanel_KhungVeHoatCanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );

            jButton_Run.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
            jButton_Run.setText("Run");
            jButton_Run.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_RunActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPane_HoatCanhLayout = new javax.swing.GroupLayout(jPane_HoatCanh);
            jPane_HoatCanh.setLayout(jPane_HoatCanhLayout);
            jPane_HoatCanhLayout.setHorizontalGroup(
                jPane_HoatCanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPane_HoatCanhLayout.createSequentialGroup()
                    .addComponent(jPanel_KhungVeHoatCanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                    .addComponent(jButton_Run)
                    .addGap(103, 103, 103))
            );
            jPane_HoatCanhLayout.setVerticalGroup(
                jPane_HoatCanhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel_KhungVeHoatCanh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPane_HoatCanhLayout.createSequentialGroup()
                    .addGap(30, 30, 30)
                    .addComponent(jButton_Run)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jTabbedPane_MenuChinh.addTab("Hoạt cảnh", jPane_HoatCanh);

            getContentPane().add(jTabbedPane_MenuChinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton_VeDoanThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDoanThangActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            DoanThang m = new DoanThang(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeDoanThangActionPerformed

    private void jButton_VeHinhChuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhChuNhatActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            HinhChuNhat m = new HinhChuNhat(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeHinhChuNhatActionPerformed

    private void jButton_VeDuongTronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDuongTronActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongTron() == true) {
            int xO = Integer.parseInt(jTextField_xTam.getText());
            int yO = Integer.parseInt(jTextField_yTam.getText());
            int r = Integer.parseInt(jTextField_BanKinh.getText());
            DuongTron m = new DuongTron(xO, yO, r);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeDuongTronActionPerformed

    private void jButton_VeNetDutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeNetDutActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            NetDut m = new NetDut(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
        //f.setLayout(null);  
    }//GEN-LAST:event_jButton_VeNetDutActionPerformed

    private void jButton_VeNetChamGachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeNetChamGachActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            NetChamGach m = new NetChamGach(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeNetChamGachActionPerformed

    private void jButton_NetHaiChamGachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NetHaiChamGachActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            NetHaiChamGach m = new NetHaiChamGach(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_NetHaiChamGachActionPerformed

    private void jButton_VeTamGiacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeTamGiacActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int xDinh = Integer.parseInt(jTextField_xDinh.getText());
        int yDinh = Integer.parseInt(jTextField_yDinh.getText());
        int canh = Integer.parseInt(jTextField_Canh.getText());
        TamGiacDeu m = new TamGiacDeu(xDinh, yDinh, canh);
        jPanel_KhungVe2D.add(m.draw());
        jPanel_KhungVe2D.repaint();
    }//GEN-LAST:event_jButton_VeTamGiacActionPerformed

    private void jButton_VeDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDiemActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        m.draw(g);
    }//GEN-LAST:event_jButton_VeDiemActionPerformed

    private void jButton_VeMuiTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeMuiTenActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            MuiTen m = new MuiTen(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeMuiTenActionPerformed

    private void jButton_Xoa2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Xoa2DActionPerformed
        jPanel_KhungVe2D.removeAll();
        jPanel_KhungVe2D.repaint();
    }//GEN-LAST:event_jButton_Xoa2DActionPerformed

    private void jButton_VeEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeEllipseActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int xO = Integer.parseInt(jTextField_Tamx.getText());
        int yO = Integer.parseInt(jTextField_Tamy.getText());
        int a = Integer.parseInt(jTextField_BanKinhNgang.getText());
        int b = Integer.parseInt(jTextField_BanKinhDoc.getText());
        Ellipse m = new Ellipse(xO, yO, a, b);
        m.draw(g);
    }//GEN-LAST:event_jButton_VeEllipseActionPerformed

    private void jButton_VeHinhHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhHopActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        HinhHop hh = new HinhHop();
        hh.nhapToaDo3D();
        ThamSoTruyenVao.nutVe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutVe.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutXoa.setBackground(Color.WHITE);
                hh.xuLyDuLieu();
                hh.draw(g);
                jTextArea_ToaDo.setText(hh.layDuLieu());
            }
        });
        ThamSoTruyenVao.nutXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutXoa.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutVe.setBackground(Color.WHITE);
                hh.xoaDuLieu();
            }
        });
    }//GEN-LAST:event_jButton_VeHinhHopActionPerformed

    private void jButton_VeHinhChopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhChopActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        HinhChop hc = new HinhChop();
        hc.nhapToaDo3D();
        ThamSoTruyenVao.nutVe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutVe.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutXoa.setBackground(Color.WHITE);
                hc.xuLyDuLieu();
                hc.draw(g);
                jTextArea_ToaDo.setText(hc.layDuLieu());
            }
        });
        ThamSoTruyenVao.nutXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutXoa.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutVe.setBackground(Color.WHITE);
                hc.xoaDuLieu();
            }
        });
    }//GEN-LAST:event_jButton_VeHinhChopActionPerformed

    private void jButton_Xoa3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Xoa3DActionPerformed
        // TODO add your handling code here:
        jPanel_KhungVe3D.repaint();
        jTextArea_ToaDo.setText("");
    }//GEN-LAST:event_jButton_Xoa3DActionPerformed

    private void jButton_TinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TinhTienActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        int dx, dy;
        dx = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập khoảng tịnh tiến dx:"));
        dy = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập khoảng tịnh tiến dy:"));
        m = TinhTien.TinhTien(m, dx, dy);
        m.draw(g);
    }//GEN-LAST:event_jButton_TinhTienActionPerformed

    private void jButton_QuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuayActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        Diem2D tam = new Diem2D();
        float gocQuay;
        tam.setX(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập hoành độ tâm:")));
        tam.setY(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập tung độ tâm:")));
        gocQuay = Float.parseFloat(JOptionPane.showInputDialog(this, "Nhập góc quay (độ):"));
        gocQuay = gocQuay * (float) Math.PI / 180;
        m = Quay.QuayTamBatKy(tam, m, gocQuay);
        m.draw(g);
    }//GEN-LAST:event_jButton_QuayActionPerformed

    private void jButton_DoiXungQuaDuongThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DoiXungQuaDuongThangActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        Diem2D a = new Diem2D();
        Diem2D b = new Diem2D();
        a.setX(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập x điểm đầu")));
        a.setY(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập y điểm đầu")));
        b.setX(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập x điểm cuối")));
        b.setY(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập y điểm cuối")));
        m = DoiXungQuaDoanThang.layDoiXung(m, a, b);
        System.out.println(m.getX() + " " + m.getY());
        m.draw(g);
        DoanThang ab = new DoanThang(a.getX(), a.getY(), b.getX(), b.getY());
        ab.draw(g);
    }//GEN-LAST:event_jButton_DoiXungQuaDuongThangActionPerformed

    private void jButton_VeHinhCauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhCauActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        HinhCau hc = new HinhCau();
        hc.nhapToaDo3D();
        ThamSoTruyenVao.nutVe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutVe.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutXoa.setBackground(Color.WHITE);
                hc.xuLyDuLieu();
                hc.draw(g);
                jTextArea_ToaDo.setText(hc.layDuLieu());
            }
        });
        ThamSoTruyenVao.nutXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutXoa.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutVe.setBackground(Color.WHITE);
                hc.xoaDuLieu();
            }
        });
    }//GEN-LAST:event_jButton_VeHinhCauActionPerformed

    public void veChongChong() {
        ThamSoTruyenVao.xChongChong = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập tọa độ x chong chóng"));
        ThamSoTruyenVao.yChongChong = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập tọa độ y chong chóng"));
        ThamSoTruyenVao.bkChongChong = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập bán kính chong chóng"));
        Graphics2D g = (Graphics2D) jPanel_KhungVe2DChuyenDong.getGraphics();
        ChongChong cc = new ChongChong(ThamSoTruyenVao.xChongChong, ThamSoTruyenVao.yChongChong, ThamSoTruyenVao.bkChongChong);
        cc.draw(g);
        jTextArea_ToaDoVat.setText(cc.inToaDo());
    }

    public void veOTo() {
        int x = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập tọa độ x bánh xe trái"));
        int y = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập tọa độ y bánh xe trái"));
        int bk = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập bán kính bánh xe"));
        Graphics2D g = (Graphics2D) jPanel_KhungVe2DChuyenDong.getGraphics();
        OTo o = new OTo(new Diem2D(x, y), bk);
        o.draw(g);
    }

    private void jButton_2DVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2DVeActionPerformed
        // TODO add your handling code here:
        if (jRadioButton_ChongChong.isSelected()) {
            veChongChong();
        } else if (jRadioButton_OTo.isSelected()) {
            veOTo();
        }
    }//GEN-LAST:event_jButton_2DVeActionPerformed

    void ttChongChong() {
        int dx = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập độ dời x"));
        int dy = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập độ dời y"));
        Graphics2D gr = (Graphics2D) jPanel_KhungVe2DChuyenDong.getGraphics();
        ChongChong cc = new ChongChong(ThamSoTruyenVao.xChongChong, ThamSoTruyenVao.yChongChong, ThamSoTruyenVao.bkChongChong);
        BufferedImage buffer = new BufferedImage(700, 500, BufferedImage.TYPE_INT_ARGB);
        Graphics g = buffer.getGraphics();
        ThamSoTruyenVao.veToaDo((Graphics2D) g);
        cc.drawTinhTien((Graphics2D) g, dx, dy);
        gr.drawImage(buffer, 0, 0, null);
        jTextArea_ToaDoVat.setText(cc.inToaDo());
    }

    void ttOTo() {
        int dx = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập độ dời x"));
        int dy = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập độ dời y"));
        Graphics2D gr = (Graphics2D) jPanel_KhungVe2DChuyenDong.getGraphics();
        OTo o = new OTo(ThamSoTruyenVao.tamBanh, ThamSoTruyenVao.bkBanh);
        BufferedImage buffer = new BufferedImage(700, 500, BufferedImage.TYPE_INT_ARGB);
        Graphics g = buffer.getGraphics();
        ThamSoTruyenVao.veToaDo((Graphics2D) g);
        o.drawTinhTien((Graphics2D) g, dx, dy);
        gr.drawImage(buffer, 0, 0, null);
    }

    private void jButton_2DTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2DTinhTienActionPerformed
        // TODO add your handling code here:
        if (jRadioButton_ChongChong.isSelected()) {
            ttChongChong();
        } else if (jRadioButton_OTo.isSelected()) {
            ttOTo();
            
        }
    }//GEN-LAST:event_jButton_2DTinhTienActionPerformed

    void quayChongChong() {
        float goc = Float.parseFloat(JOptionPane.showInputDialog(this, "Nhập góc quay"));
        Graphics2D gr = (Graphics2D) jPanel_KhungVe2DChuyenDong.getGraphics();
        ChongChong cc = new ChongChong(ThamSoTruyenVao.xChongChong, ThamSoTruyenVao.yChongChong, ThamSoTruyenVao.bkChongChong);
        BufferedImage buffer = new BufferedImage(700, 500, BufferedImage.TYPE_INT_ARGB);
        Graphics g = buffer.getGraphics();
        ThamSoTruyenVao.veToaDo((Graphics2D) g);
        cc.drawQuay((Graphics2D) g, goc);
        gr.drawImage(buffer, 0, 0, null);
        jTextArea_ToaDoVat.setText(cc.inToaDo());
    }

    private void jButton_2QuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2QuayActionPerformed
        // TODO add your handling code here:
        if (jRadioButton_ChongChong.isSelected()) {
            quayChongChong();
        }
    }//GEN-LAST:event_jButton_2QuayActionPerformed

    private void jButton_VeDiem3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDiem3DActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        A.nhapToaDo3D();
        ThamSoTruyenVao.nutVe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutVe.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutXoa.setBackground(Color.WHITE);
                A.xuLyDuLieu();
                A.draw(g);
                jTextArea_ToaDo.setText(A.layDuLieu());
            }
        });
        ThamSoTruyenVao.nutXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutXoa.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutVe.setBackground(Color.WHITE);
                A.xoaDuLieu();
            }
        });
    }//GEN-LAST:event_jButton_VeDiem3DActionPerformed

    private void jButton_ĐoiXungQuaDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ĐoiXungQuaDiemActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        Diem3D kq = new Diem3D();
        Diem3D tam = new Diem3D();
        int x = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập x tâm đối xứng:"));
        tam.setX(x);
        int y = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập y tâm đối xứng:"));
        tam.setY(y);
        int z = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập z tâm đối xứng:"));
        tam.setZ(z);
        kq = DoiXungQuaDiem.LayDoiXung(A, tam);
        kq.draw(g);
        String str = "\n\t\tTỌA ĐỘ ĐIỂM\n\n";
        str += "\tA (" + A.getX() + ", " + A.getY() + ", " + A.getZ() + ")";
        str += "\n\t\tTÂM\n\n";
        str += "\tS (" + x + ", " + y + ", " + z + ")";
        str += "\n\t\tĐIỂM SAU ĐỐI XỨNG\n\n";
        str += "\tA' (" + kq.getX() + ", " + kq.getY() + ", " + kq.getZ() + ")";
        jTextArea_ToaDo.setText(str);
    }//GEN-LAST:event_jButton_ĐoiXungQuaDiemActionPerformed

    void tpChongChong() {
        float sx = Float.parseFloat(JOptionPane.showInputDialog(this, "Nhập tỉ lệ co giãn theo trục x"));
        float sy = Float.parseFloat(JOptionPane.showInputDialog(this, "Nhập tỉ lệ co giãn theo trục y"));
        Graphics2D gr = (Graphics2D) jPanel_KhungVe2DChuyenDong.getGraphics();
        ChongChong cc = new ChongChong(ThamSoTruyenVao.xChongChong, ThamSoTruyenVao.yChongChong, ThamSoTruyenVao.bkChongChong);
        BufferedImage buffer = new BufferedImage(700, 500, BufferedImage.TYPE_INT_ARGB);
        Graphics g = buffer.getGraphics();
        ThamSoTruyenVao.veToaDo((Graphics2D) g);
        cc.drawThuPhong((Graphics2D) g, sx, sy);
        gr.drawImage(buffer, 0, 0, null);
        jTextArea_ToaDoVat.setText(cc.inToaDo());
    }

    private void jButton_2DThuPhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2DThuPhongActionPerformed
        // TODO add your handling code here:
        if (jRadioButton_ChongChong.isSelected()) {
            tpChongChong();
        }
    }//GEN-LAST:event_jButton_2DThuPhongActionPerformed

    private void jButton_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RunActionPerformed
        // TODO add your handling code here:
        OTo o = new OTo(new Diem2D(-70, -35), 7);
        ChongChong cc1 = new ChongChong(-50, 20, 15);
        ChongChong cc2 = new ChongChong(50, 20, 15);
        int j = 0;
        Graphics2D gr = (Graphics2D)jPanel_KhungVeHoatCanh.getGraphics();
        for (int i = 0; i < 140; i++) {
            BufferedImage buffer = new BufferedImage(700, 500, BufferedImage.TYPE_INT_ARGB);
            Graphics g = buffer.getGraphics();
            ThamSoTruyenVao.veToaDo((Graphics2D) g);
            if (j < -90) {
                cc1 = new ChongChong(-50, 20, 15);
                cc2 = new ChongChong(50, 20, 15);
            }
            cc1.drawQuay((Graphics2D) g, j);
            cc2.drawQuay((Graphics2D) g, j);
            j -= 15;
            o.drawTinhTien((Graphics2D) g, 1, 0);
            gr.drawImage(buffer, 0, 0, null);
            try {
                Thread.sleep(20);
            } catch (InterruptedException ex) {
                Logger.getLogger(GiaoDienChinh.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton_RunActionPerformed

    public void dxChongChong () {
        int x1 = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập x điểm đầu"));
        int y1 = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập y diểm đầu"));
        int x2 = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập x điểm cuối"));
        int y2 = Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập y diem cuối"));
        Graphics2D gr = (Graphics2D) jPanel_KhungVe2DChuyenDong.getGraphics();
        ChongChong cc = new ChongChong(ThamSoTruyenVao.xChongChong, ThamSoTruyenVao.yChongChong, ThamSoTruyenVao.bkChongChong);
        BufferedImage buffer = new BufferedImage(700, 500, BufferedImage.TYPE_INT_ARGB);
        Graphics g = buffer.getGraphics();
        ThamSoTruyenVao.veToaDo((Graphics2D) g);
        cc.drawDoiXung((Graphics2D) g, new Diem2D(x1, y1), new Diem2D(x2, y2));
        gr.drawImage(buffer, 0, 0, null);
        jTextArea_ToaDoVat.setText(cc.inToaDo());
    }
    
    private void jButton_2DDoiXungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_2DDoiXungActionPerformed
        // TODO add your handling code here:
        if (jRadioButton_ChongChong.isSelected()) {
            dxChongChong();
        }
    }//GEN-LAST:event_jButton_2DDoiXungActionPerformed

    boolean rangBuocDuLieuDuongThang() {
        String x1 = jTextField_x1.getText();
        String y1 = jTextField_y1.getText();
        String x2 = jTextField_x2.getText();
        String y2 = jTextField_y2.getText();
        if (!x1.equals("") && !x2.equals("") && !y1.equals("") && !y2.equals("")) {
            return true;
        }
        return false;
    }

    boolean rangBuocDuLieuDuongTron() {
        String xO = jTextField_xTam.getText();
        String yO = jTextField_yTam.getText();
        String r = jTextField_BanKinh.getText();
        if (!xO.equals("") && !yO.equals("") && !r.equals("")) {
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup_Vat2DChuyenDong;
    private javax.swing.JButton jButton_2DDoiXung;
    private javax.swing.JButton jButton_2DThuPhong;
    private javax.swing.JButton jButton_2DTinhTien;
    private javax.swing.JButton jButton_2DVe;
    private javax.swing.JButton jButton_2Quay;
    private javax.swing.JButton jButton_DoiXungQuaDuongThang;
    private javax.swing.JButton jButton_NetHaiChamGach;
    private javax.swing.JButton jButton_Quay;
    private javax.swing.JButton jButton_Run;
    private javax.swing.JButton jButton_TinhTien;
    private javax.swing.JButton jButton_VeDiem;
    private javax.swing.JButton jButton_VeDiem3D;
    private javax.swing.JButton jButton_VeDoanThang;
    private javax.swing.JButton jButton_VeDuongTron;
    private javax.swing.JButton jButton_VeEllipse;
    private javax.swing.JButton jButton_VeHinhCau;
    private javax.swing.JButton jButton_VeHinhChop;
    private javax.swing.JButton jButton_VeHinhChuNhat;
    private javax.swing.JButton jButton_VeHinhHop;
    private javax.swing.JButton jButton_VeMuiTen;
    private javax.swing.JButton jButton_VeNetChamGach;
    private javax.swing.JButton jButton_VeNetDut;
    private javax.swing.JButton jButton_VeTamGiac;
    private javax.swing.JButton jButton_Xoa2D;
    private javax.swing.JButton jButton_Xoa3D;
    private javax.swing.JButton jButton_ĐoiXungQuaDiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel_BanKinh;
    private javax.swing.JLabel jLabel_BanKinhDoc;
    private javax.swing.JLabel jLabel_BanKinhNgang;
    private javax.swing.JLabel jLabel_Canh;
    private javax.swing.JLabel jLabel_Tamx;
    private javax.swing.JLabel jLabel_Tamy;
    private javax.swing.JLabel jLabel_x;
    private javax.swing.JLabel jLabel_xDinh;
    private javax.swing.JLabel jLabel_xTam;
    private javax.swing.JLabel jLabel_y;
    private javax.swing.JLabel jLabel_yDinh;
    private javax.swing.JLabel jLabel_yTam;
    private javax.swing.JPanel jPane_HoatCanh;
    private javax.swing.JPanel jPanel_2D;
    private javax.swing.JPanel jPanel_2DChuyenDong;
    private javax.swing.JPanel jPanel_3D;
    private javax.swing.JPanel jPanel_BienDoi2D;
    private javax.swing.JPanel jPanel_ChucNang2DChuyenDong;
    private javax.swing.JPanel jPanel_Diem;
    private javax.swing.JPanel jPanel_DoanThang;
    private javax.swing.JPanel jPanel_DuongTron;
    private javax.swing.JPanel jPanel_Ellipse;
    private javax.swing.JPanel jPanel_KhungVe2D;
    private javax.swing.JPanel jPanel_KhungVe2DChuyenDong;
    private javax.swing.JPanel jPanel_KhungVe3D;
    private javax.swing.JPanel jPanel_KhungVeHoatCanh;
    private javax.swing.JPanel jPanel_Menu2DChuyenDong;
    private javax.swing.JPanel jPanel_Menu3D;
    private javax.swing.JPanel jPanel_MenuDoanThang;
    private javax.swing.JPanel jPanel_TamGiacDeu;
    private javax.swing.JRadioButton jRadioButton_ChongChong;
    private javax.swing.JRadioButton jRadioButton_OTo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_ToaDo;
    private javax.swing.JTabbedPane jTabbedPane_Menu2D;
    private javax.swing.JTabbedPane jTabbedPane_MenuChinh;
    private javax.swing.JTextArea jTextArea_ToaDo;
    private javax.swing.JTextArea jTextArea_ToaDoVat;
    private javax.swing.JTextField jTextField_BanKinh;
    private javax.swing.JTextField jTextField_BanKinhDoc;
    private javax.swing.JTextField jTextField_BanKinhNgang;
    private javax.swing.JTextField jTextField_Canh;
    private javax.swing.JTextField jTextField_Tamx;
    private javax.swing.JTextField jTextField_Tamy;
    private javax.swing.JTextField jTextField_x;
    private javax.swing.JTextField jTextField_x1;
    private javax.swing.JTextField jTextField_x2;
    private javax.swing.JTextField jTextField_xDinh;
    private javax.swing.JTextField jTextField_xTam;
    private javax.swing.JTextField jTextField_y;
    private javax.swing.JTextField jTextField_y1;
    private javax.swing.JTextField jTextField_y2;
    private javax.swing.JTextField jTextField_yDinh;
    private javax.swing.JTextField jTextField_yTam;
    // End of variables declaration//GEN-END:variables
}
