/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import biendoi2D.DoiXungQuaDoanThang;
import biendoi2D.Quay;
import biendoi2D.TinhTien;
import model2D.ThamSoTruyenVao;
import model2D.Diem2D;
import model2D.DoanThang;
import model2D.DuongTron;
import model2D.Ellipse;
import model2D.HinhChuNhat;
import model2D.MuiTen;
import model2D.NetChamGach;
import model2D.NetDut;
import model2D.NetHaiChamGach;
import model2D.TamGiacDeu;
import java.awt.Graphics;
import java.awt.Dimension;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model3D.HinhChop;
import model3D.HinhHop;

/**
 *
 * @author Apple Bee
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    public GiaoDienChinh() {
        initComponents();
        this.setLocationRelativeTo(null); //Hiển thị cửa sổ lên vị trí giữa màn hình
        this.setDefaultCloseOperation(EXIT_ON_CLOSE); //Thiết lập việc tắt chương trình khi click nào nút X trên thanh tiêu đề. Nếu không thêm dòng đó vào thì khi bấm nút X, cửa sổ chương trình vẫn sẽ biến mất nhưng bản thân chương trình thì vẫn chạy ngầm bên dưới chứ không tắt hẳn.
        jPanel_KhungVe2D.setBackground(Color.BLUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jTabbedPane_MenuChinh = new javax.swing.JTabbedPane();
        jPanel_BT2D = new javax.swing.JPanel();
        jTabbedPane_Menu2D = new javax.swing.JTabbedPane();
        Diem = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField_x = new javax.swing.JTextField();
        jTextField_y = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton_VeDiem = new javax.swing.JButton();
        jButton_TinhTien = new javax.swing.JButton();
        jButton_Quay = new javax.swing.JButton();
        jButton_DoiXungQuaDuongThang = new javax.swing.JButton();
        TamGiacDeu = new javax.swing.JPanel();
        jTextField_xDinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField_yDinh = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField_canh = new javax.swing.JTextField();
        jButton_VeTamGiac = new javax.swing.JButton();
        HinhTron = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_xO = new javax.swing.JTextField();
        jTextField_yO = new javax.swing.JTextField();
        jButton_VeDuongTron = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField_r = new javax.swing.JTextField();
        Ellipse = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_xC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_yC = new javax.swing.JTextField();
        jTextField_a = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButton_VeEllipse = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jTextField_b = new javax.swing.JTextField();
        DoanThang = new javax.swing.JPanel();
        jTextField_x1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_y1 = new javax.swing.JTextField();
        jTextField_x2 = new javax.swing.JTextField();
        jTextField_y2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton_VeDoanThang = new javax.swing.JButton();
        jButton_VeNetDut = new javax.swing.JButton();
        jButton_NetChamGach = new javax.swing.JButton();
        jButton_NetHaiChamGach = new javax.swing.JButton();
        jButton_VeMuiTen = new javax.swing.JButton();
        jButton_VeHinhChuNhat = new javax.swing.JButton();
        jPanel_KhungVe2D = new javax.swing.JPanel(){
            private static final long serialVersionUID = 1L;
            @Override
            protected void paintComponent(Graphics arg0) {
                // TODO Auto-generated method stub
                super.paintComponent(arg0);
                arg0.setColor(Color.LIGHT_GRAY);
                for (int i = 5; i< ThamSoTruyenVao.backgroundWidth; i += 5) {
                    arg0.drawLine(i,0,i,ThamSoTruyenVao.backgroundHeight);
                }
                for (int i = 5; i< ThamSoTruyenVao.backgroundHeight; i += 5) {
                    arg0.drawLine(0,i,ThamSoTruyenVao.backgroundWidth, i);
                }
                setBackground(Color.WHITE);
                arg0.setColor(Color.BLACK);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 - 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 + 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawString("O", ThamSoTruyenVao.backgroundWidth/2 + 5, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("10", ThamSoTruyenVao.backgroundWidth/2 + 50, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("20", ThamSoTruyenVao.backgroundWidth/2 + 100, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("30", ThamSoTruyenVao.backgroundWidth/2 + 150, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("40", ThamSoTruyenVao.backgroundWidth/2 + 200, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("x", ThamSoTruyenVao.backgroundWidth - 7, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("y", ThamSoTruyenVao.backgroundWidth/2 + 5, 20);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, 0, ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2);//y+
                for (int i = 1; i < ThamSoTruyenVao.backgroundWidth/100; i++) { //vach don vi
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 - 2, ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 + 2);
                }
                for (int i = 1; i < ThamSoTruyenVao.backgroundHeight/100; i++) { //vach don vi
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 2, i * 50, ThamSoTruyenVao.backgroundWidth/2 + 2, i * 50);
                }
                arg0.setColor(Color.BLUE);
                for(int i=ThamSoTruyenVao.backgroundHeight/2;i<=ThamSoTruyenVao.backgroundHeight;i+=6){//y-
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, i, ThamSoTruyenVao.backgroundWidth/2,i+3);
                }
                arg0.setColor(Color.BLACK);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);//x+
                arg0.setColor(Color.BLUE);
                for(int i=ThamSoTruyenVao.backgroundWidth/2;i>=0;i-=6){//x-
                    arg0.drawLine(i,ThamSoTruyenVao.backgroundHeight/2,i-3,ThamSoTruyenVao.backgroundHeight/2);
                }

                //        arg0.setColor(Color.BLACK);
                //        arg0.drawLine(0,BasicParam.backgroundHeight,BasicParam.backgroundWidth/2,BasicParam.backgroundHeight/2);//z+
                //        int l = BasicParam.backgroundHeight / 2;
                //        arg0.setColor(Color.BLUE);
                //        for (int i = BasicParam.backgroundWidth / 2; i <= BasicParam.backgroundWidth; i += 6) {
                    //            arg0.drawLine(i + 3, l - 3, i + 6, l - 6);
                    //            l -= 6;
                    //        }

            }
        };
        jButton_Xoa2D = new javax.swing.JButton();
        jPanel_3D = new javax.swing.JPanel();
        jPanel_KhungVe3D = new javax.swing.JPanel(){
            private static final long serialVersionUID = 1L;
            @Override
            protected void paintComponent(Graphics arg0) {
                // TODO Auto-generated method stub
                super.paintComponent(arg0);
                //        arg0.setColor(Color.LIGHT_GRAY);
                //        for (int i = 5; i< BasicParam.backgroundWidth; i += 5) {
                    //            arg0.drawLine(i,0,i,BasicParam.backgroundHeight);
                    //        }
                //        for (int i = 5; i< BasicParam.backgroundHeight; i += 5) {
                    //            arg0.drawLine(0,i,BasicParam.backgroundWidth, i);
                    //        }
                setBackground(Color.WHITE);
                arg0.setColor(Color.BLACK);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + 5, 10, ThamSoTruyenVao.backgroundWidth/2, 0);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 - 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawLine(ThamSoTruyenVao.backgroundWidth - 10, ThamSoTruyenVao.backgroundHeight/2 + 5, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);
                arg0.drawString("O", ThamSoTruyenVao.backgroundWidth/2 + 5, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("10", ThamSoTruyenVao.backgroundWidth/2 + 50, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("20", ThamSoTruyenVao.backgroundWidth/2 + 100, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("30", ThamSoTruyenVao.backgroundWidth/2 + 150, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("40", ThamSoTruyenVao.backgroundWidth/2 + 200, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("x", ThamSoTruyenVao.backgroundWidth - 5, ThamSoTruyenVao.backgroundHeight/2 + 20);
                arg0.drawString("z", ThamSoTruyenVao.backgroundWidth/2 + 5, 20);
                //        arg0.drawString(">", BasicParam.backgroundWidth, BasicParam.backgroundHeight/2 + 5);
                //        arg0.drawString("/\\", BasicParam.backgroundWidth/2 - 3, 10);
                    arg0.drawString("y", 5, ThamSoTruyenVao.backgroundHeight - 20);
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, 0, ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2);//y+
                    for (int i = 1; i < ThamSoTruyenVao.backgroundWidth/100; i++) { //vach don vi
                        arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 - 2, ThamSoTruyenVao.backgroundWidth/2 + i * 50, ThamSoTruyenVao.backgroundHeight/2 + 2);
                    }
                    for (int i = 1; i < ThamSoTruyenVao.backgroundHeight/100; i++) { //vach don vi
                        arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2 - 2, i * 50, ThamSoTruyenVao.backgroundWidth/2 + 2, i * 50);
                    }
                    arg0.setColor(Color.BLUE);
                    for(int i=ThamSoTruyenVao.backgroundHeight/2;i<=ThamSoTruyenVao.backgroundHeight;i+=6){//y-
                        arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, i, ThamSoTruyenVao.backgroundWidth/2,i+3);
                    }
                    arg0.setColor(Color.BLACK);
                    arg0.drawLine(ThamSoTruyenVao.backgroundWidth/2, ThamSoTruyenVao.backgroundHeight/2, ThamSoTruyenVao.backgroundWidth, ThamSoTruyenVao.backgroundHeight/2);//x+
                    arg0.setColor(Color.BLUE);
                    for(int i=ThamSoTruyenVao.backgroundWidth/2;i>=0;i-=6){//x-
                        arg0.drawLine(i,ThamSoTruyenVao.backgroundHeight/2,i-3,ThamSoTruyenVao.backgroundHeight/2);
                    }

                    arg0.setColor(Color.BLACK);
                    arg0.drawLine(0,ThamSoTruyenVao.backgroundHeight,ThamSoTruyenVao.backgroundWidth/2,ThamSoTruyenVao.backgroundHeight/2);//z+
                    int l = ThamSoTruyenVao.backgroundHeight / 2;
                    arg0.setColor(Color.BLUE);
                    for (int i = ThamSoTruyenVao.backgroundWidth / 2; i <= ThamSoTruyenVao.backgroundWidth; i += 6) {
                        arg0.drawLine(i + 3, l - 3, i + 6, l - 6);
                        l -= 6;
                    }

                }
            };
            jPanel2 = new javax.swing.JPanel();
            jButton_VeHinhHop = new javax.swing.JButton();
            jButton_VeHinhChop = new javax.swing.JButton();
            jButton_Xoa3D = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTextArea_ToaDo = new javax.swing.JTextArea();
            jTextArea_ToaDo.setEditable(false);

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
            setBackground(new java.awt.Color(0, 204, 255));
            getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel8.setForeground(new java.awt.Color(153, 153, 153));
            jLabel8.setText("1 đơn vị = 5 pixel");
            getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

            jPanel_BT2D.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jTabbedPane_Menu2D.setBackground(new java.awt.Color(0, 204, 255));

            Diem.setBackground(new java.awt.Color(0, 204, 255));
            Diem.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel12.setText("x:");
            Diem.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 30, -1));
            Diem.add(jTextField_x, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 112, -1));
            Diem.add(jTextField_y, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 112, -1));

            jLabel13.setText("y:");
            Diem.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));

            jButton_VeDiem.setText("Vẽ điểm");
            jButton_VeDiem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDiemActionPerformed(evt);
                }
            });
            Diem.add(jButton_VeDiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 110, 40));

            jButton_TinhTien.setText("Tịnh tiến");
            jButton_TinhTien.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_TinhTienActionPerformed(evt);
                }
            });
            Diem.add(jButton_TinhTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 233, -1, 30));

            jButton_Quay.setText("Quay");
            jButton_Quay.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_QuayActionPerformed(evt);
                }
            });
            Diem.add(jButton_Quay, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 273, -1, 30));

            jButton_DoiXungQuaDuongThang.setText("Đối xứng qua đường thẳng");
            jButton_DoiXungQuaDuongThang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_DoiXungQuaDuongThangActionPerformed(evt);
                }
            });
            Diem.add(jButton_DoiXungQuaDuongThang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, 30));

            jTabbedPane_Menu2D.addTab("Điểm", Diem);

            TamGiacDeu.setBackground(new java.awt.Color(0, 204, 255));
            TamGiacDeu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            TamGiacDeu.add(jTextField_xDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 112, -1));

            jLabel9.setText("x đỉnh:");
            TamGiacDeu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

            jLabel10.setText("y đỉnh:");
            TamGiacDeu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, -1, -1));
            TamGiacDeu.add(jTextField_yDinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 112, -1));

            jLabel11.setText("a:");
            TamGiacDeu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));
            TamGiacDeu.add(jTextField_canh, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 112, -1));

            jButton_VeTamGiac.setText("Vẽ tam giác");
            jButton_VeTamGiac.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeTamGiacActionPerformed(evt);
                }
            });
            TamGiacDeu.add(jButton_VeTamGiac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 160, 40));

            jTabbedPane_Menu2D.addTab("Tam giác đều", TamGiacDeu);

            HinhTron.setBackground(new java.awt.Color(0, 204, 255));
            HinhTron.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jLabel5.setText("xO:");
            HinhTron.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

            jLabel6.setText("yO:");
            HinhTron.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, -1));
            HinhTron.add(jTextField_xO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 112, -1));
            HinhTron.add(jTextField_yO, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 112, -1));

            jButton_VeDuongTron.setText("Vẽ đường tròn");
            jButton_VeDuongTron.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDuongTronActionPerformed(evt);
                }
            });
            HinhTron.add(jButton_VeDuongTron, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 120, 30));

            jLabel7.setText("r:");
            HinhTron.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));
            HinhTron.add(jTextField_r, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 112, -1));

            jTabbedPane_Menu2D.addTab("Đường tròn", HinhTron);

            Ellipse.setBackground(new java.awt.Color(0, 204, 255));

            jLabel14.setText("xO:");

            jLabel15.setText("yO:");

            jLabel16.setText("a:");

            jButton_VeEllipse.setText("Vẽ Ellipse");
            jButton_VeEllipse.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeEllipseActionPerformed(evt);
                }
            });

            jLabel17.setText("b:");

            javax.swing.GroupLayout EllipseLayout = new javax.swing.GroupLayout(Ellipse);
            Ellipse.setLayout(EllipseLayout);
            EllipseLayout.setHorizontalGroup(
                EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EllipseLayout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EllipseLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField_yC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(EllipseLayout.createSequentialGroup()
                            .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel16)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField_b, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_a, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(EllipseLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextField_xC, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(168, 168, 168))
                .addGroup(EllipseLayout.createSequentialGroup()
                    .addGap(174, 174, 174)
                    .addComponent(jButton_VeEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );
            EllipseLayout.setVerticalGroup(
                EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EllipseLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel14)
                        .addComponent(jTextField_xC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jTextField_yC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(34, 34, 34)
                    .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jTextField_a, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(EllipseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_b, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(49, 49, 49)
                    .addComponent(jButton_VeEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(125, Short.MAX_VALUE))
            );

            jTabbedPane_Menu2D.addTab("Ellipse", Ellipse);

            DoanThang.setBackground(new java.awt.Color(0, 204, 255));
            DoanThang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
            DoanThang.add(jTextField_x1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 116, -1));

            jLabel1.setText("x1:");
            DoanThang.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

            jLabel2.setText("y1:");
            DoanThang.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

            jLabel3.setText("x2:");
            DoanThang.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

            jLabel4.setText("y2:");
            DoanThang.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, -1, -1));
            DoanThang.add(jTextField_y1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 116, -1));
            DoanThang.add(jTextField_x2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 116, -1));
            DoanThang.add(jTextField_y2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 116, -1));

            jPanel1.setBackground(new java.awt.Color(0, 204, 255));
            jPanel1.setLayout(new java.awt.GridLayout(3, 2, 20, 20));

            jButton_VeDoanThang.setText("Vẽ đoạn thẳng");
            jButton_VeDoanThang.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeDoanThangActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_VeDoanThang);

            jButton_VeNetDut.setText("Vẽ nét đứt");
            jButton_VeNetDut.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeNetDutActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_VeNetDut);

            jButton_NetChamGach.setText("Vẽ nét chấm gạch");
            jButton_NetChamGach.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_NetChamGachActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_NetChamGach);

            jButton_NetHaiChamGach.setText("Vẽ nét hai chấm gạch");
            jButton_NetHaiChamGach.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_NetHaiChamGachActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_NetHaiChamGach);

            jButton_VeMuiTen.setText("Vẽ mũi tên");
            jButton_VeMuiTen.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeMuiTenActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_VeMuiTen);

            jButton_VeHinhChuNhat.setText("Vẽ hình chữ nhật");
            jButton_VeHinhChuNhat.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhChuNhatActionPerformed(evt);
                }
            });
            jPanel1.add(jButton_VeHinhChuNhat);

            DoanThang.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 360, 170));

            jTabbedPane_Menu2D.addTab("Đoạn thẳng", DoanThang);

            jPanel_BT2D.add(jTabbedPane_Menu2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 450));

            jPanel_KhungVe2D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout jPanel_KhungVe2DLayout = new javax.swing.GroupLayout(jPanel_KhungVe2D);
            jPanel_KhungVe2D.setLayout(jPanel_KhungVe2DLayout);
            jPanel_KhungVe2DLayout.setHorizontalGroup(
                jPanel_KhungVe2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );
            jPanel_KhungVe2DLayout.setVerticalGroup(
                jPanel_KhungVe2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );

            jPanel_BT2D.add(jPanel_KhungVe2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 500, -1));

            jButton_Xoa2D.setText("Xóa tất cả");
            jButton_Xoa2D.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_Xoa2DActionPerformed(evt);
                }
            });
            jPanel_BT2D.add(jButton_Xoa2D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 470, 50));

            jTabbedPane_MenuChinh.addTab("Bài tập vẽ 2D", jPanel_BT2D);

            jPanel_3D.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

            jPanel_KhungVe3D.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

            javax.swing.GroupLayout jPanel_KhungVe3DLayout = new javax.swing.GroupLayout(jPanel_KhungVe3D);
            jPanel_KhungVe3D.setLayout(jPanel_KhungVe3DLayout);
            jPanel_KhungVe3DLayout.setHorizontalGroup(
                jPanel_KhungVe3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 508, Short.MAX_VALUE)
            );
            jPanel_KhungVe3DLayout.setVerticalGroup(
                jPanel_KhungVe3DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 498, Short.MAX_VALUE)
            );

            jPanel_3D.add(jPanel_KhungVe3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 510, -1));

            jPanel2.setBackground(new java.awt.Color(0, 204, 204));
            jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());

            jButton_VeHinhHop.setBackground(new java.awt.Color(247, 247, 247));
            jButton_VeHinhHop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinhhop.png"))); // NOI18N
            jButton_VeHinhHop.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhHopActionPerformed(evt);
                }
            });

            jButton_VeHinhChop.setBackground(new java.awt.Color(247, 247, 247));
            jButton_VeHinhChop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hinhchop.PNG"))); // NOI18N
            jButton_VeHinhChop.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_VeHinhChopActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jButton_VeHinhHop, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton_VeHinhChop)
                    .addContainerGap(201, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton_VeHinhHop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_VeHinhChop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(32, Short.MAX_VALUE))
            );

            jPanel_3D.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 160));

            jButton_Xoa3D.setText("Xóa tất cả");
            jButton_Xoa3D.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton_Xoa3DActionPerformed(evt);
                }
            });
            jPanel_3D.add(jButton_Xoa3D, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 450, 460, 50));

            jTextArea_ToaDo.setBackground(new java.awt.Color(51, 51, 51));
            jTextArea_ToaDo.setColumns(20);
            jTextArea_ToaDo.setForeground(new java.awt.Color(255, 255, 255));
            jTextArea_ToaDo.setRows(5);
            jScrollPane1.setViewportView(jTextArea_ToaDo);

            jPanel_3D.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 460, 290));

            jTabbedPane_MenuChinh.addTab("Vẽ 3D", jPanel_3D);

            getContentPane().add(jTabbedPane_MenuChinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton_VeDoanThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDoanThangActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            DoanThang m = new DoanThang(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeDoanThangActionPerformed

    private void jButton_VeHinhChuNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhChuNhatActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            HinhChuNhat m = new HinhChuNhat(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeHinhChuNhatActionPerformed

    private void jButton_VeDuongTronActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDuongTronActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongTron() == true) {
            int xO = Integer.parseInt(jTextField_xO.getText());
            int yO = Integer.parseInt(jTextField_yO.getText());
            int r = Integer.parseInt(jTextField_r.getText());
            DuongTron m = new DuongTron(xO, yO, r);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeDuongTronActionPerformed

    private void jButton_VeNetDutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeNetDutActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            NetDut m = new NetDut(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
        //f.setLayout(null);  
    }//GEN-LAST:event_jButton_VeNetDutActionPerformed

    private void jButton_NetChamGachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NetChamGachActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            NetChamGach m = new NetChamGach(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_NetChamGachActionPerformed

    private void jButton_NetHaiChamGachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NetHaiChamGachActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            NetHaiChamGach m = new NetHaiChamGach(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_NetHaiChamGachActionPerformed

    private void jButton_VeTamGiacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeTamGiacActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int xDinh = Integer.parseInt(jTextField_xDinh.getText());
        int yDinh = Integer.parseInt(jTextField_yDinh.getText());
        int canh = Integer.parseInt(jTextField_canh.getText());
        TamGiacDeu m = new TamGiacDeu(xDinh, yDinh, canh);
        jPanel_KhungVe2D.add(m.draw());
        jPanel_KhungVe2D.repaint();
        return;
    }//GEN-LAST:event_jButton_VeTamGiacActionPerformed

    private void jButton_VeDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeDiemActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        m.draw(g);
        return;
    }//GEN-LAST:event_jButton_VeDiemActionPerformed

    private void jButton_VeMuiTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeMuiTenActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        if (rangBuocDuLieuDuongThang() == true) {
            int x1 = Integer.parseInt(jTextField_x1.getText());
            int y1 = Integer.parseInt(jTextField_y1.getText());
            int x2 = Integer.parseInt(jTextField_x2.getText());
            int y2 = Integer.parseInt(jTextField_y2.getText());
            MuiTen m = new MuiTen(x1, y1, x2, y2);
            m.draw(g);
            return;
        }
        JOptionPane.showMessageDialog(this, "Toa do khong duoc bo trong!");
    }//GEN-LAST:event_jButton_VeMuiTenActionPerformed

    private void jButton_Xoa2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Xoa2DActionPerformed
        jPanel_KhungVe2D.removeAll();
        jPanel_KhungVe2D.repaint();
    }//GEN-LAST:event_jButton_Xoa2DActionPerformed

    private void jButton_VeEllipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeEllipseActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int xO = Integer.parseInt(jTextField_xC.getText());
        int yO = Integer.parseInt(jTextField_yC.getText());
        int a = Integer.parseInt(jTextField_a.getText());
        int b = Integer.parseInt(jTextField_b.getText());
        Ellipse m = new Ellipse(xO, yO, a, b);
        m.draw(g);
        return;
    }//GEN-LAST:event_jButton_VeEllipseActionPerformed

    private void jButton_VeHinhHopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhHopActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        HinhHop hh = new HinhHop();
        hh.nhapToaDo3D();
        ThamSoTruyenVao.nutVe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutVe.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutXoa.setBackground(Color.WHITE);
                hh.xuLyDuLieu();
                hh.draw(g);
                jTextArea_ToaDo.setText(hh.layDuLieu());
            }
        });
        ThamSoTruyenVao.nutXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutXoa.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutVe.setBackground(Color.WHITE);
                hh.xoaDuLieu();
            }
        });
    }//GEN-LAST:event_jButton_VeHinhHopActionPerformed

    private void jButton_VeHinhChopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_VeHinhChopActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe3D.getGraphics();
        HinhChop hc = new HinhChop();
        hc.nhapToaDo3D();
        ThamSoTruyenVao.nutVe.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutVe.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutXoa.setBackground(Color.WHITE);
                hc.xuLyDuLieu();
                hc.draw(g);
                jTextArea_ToaDo.setText(hc.layDuLieu());
            }
        });
        ThamSoTruyenVao.nutXoa.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                ThamSoTruyenVao.nutXoa.setBackground(Color.MAGENTA);
                ThamSoTruyenVao.nutVe.setBackground(Color.WHITE);
                hc.xoaDuLieu();
            }
        });
    }//GEN-LAST:event_jButton_VeHinhChopActionPerformed

    private void jButton_Xoa3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Xoa3DActionPerformed
        // TODO add your handling code here:
        jPanel_KhungVe3D.repaint();
        jTextArea_ToaDo.setText("");
    }//GEN-LAST:event_jButton_Xoa3DActionPerformed

    private void jButton_TinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TinhTienActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        
        m = TinhTien.TinhTien(m, 10, 0);
        m.draw(g);
            
        return;
    }//GEN-LAST:event_jButton_TinhTienActionPerformed

    private void jButton_QuayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuayActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        Diem2D tam = new Diem2D(0, 10);
        m.draw(g);
        m = Quay.QuayTamBatKy(tam, m, -(Math.PI) / 2);
        m.draw(g);
        return;
    }//GEN-LAST:event_jButton_QuayActionPerformed

    private void jButton_DoiXungQuaDuongThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DoiXungQuaDuongThangActionPerformed
        // TODO add your handling code here:
        Graphics2D g = (Graphics2D) jPanel_KhungVe2D.getGraphics();
        int x = Integer.parseInt(jTextField_x.getText());
        int y = Integer.parseInt(jTextField_y.getText());
        Diem2D m = new Diem2D(x, y);
        Diem2D a = new Diem2D();
        Diem2D b = new Diem2D();
        a.setX(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập x điểm đầu")));
        a.setY(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập y điểm đầu")));
        b.setX(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập x điểm cuối")));
        b.setY(Integer.parseInt(JOptionPane.showInputDialog(this, "Nhập y điểm cuối")));
        m = DoiXungQuaDoanThang.layDoiXung(m, a , b);
        System.out.println(m.getX() + " " + m.getY());
        m.draw(g);
        DoanThang ab = new DoanThang(a.getX(), a.getY(), b.getX(), b.getY());
        ab.draw(g);
    }//GEN-LAST:event_jButton_DoiXungQuaDuongThangActionPerformed

    boolean rangBuocDuLieuDuongThang() {
        String x1 = jTextField_x1.getText();
        String y1 = jTextField_y1.getText();
        String x2 = jTextField_x2.getText();
        String y2 = jTextField_y2.getText();
        if (!x1.equals("") && !x2.equals("") && !y1.equals("") && !y2.equals("")) {
            return true;
        }
        return false;
    }

    boolean rangBuocDuLieuDuongTron() {
        String xO = jTextField_xO.getText();
        String yO = jTextField_yO.getText();
        String r = jTextField_r.getText();
        if (!xO.equals("") && !yO.equals("") && !r.equals("")) {
            return true;
        }
        return false;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Diem;
    private javax.swing.JPanel DoanThang;
    private javax.swing.JPanel Ellipse;
    private javax.swing.JPanel HinhTron;
    private javax.swing.JPanel TamGiacDeu;
    private javax.swing.JButton jButton_DoiXungQuaDuongThang;
    private javax.swing.JButton jButton_NetChamGach;
    private javax.swing.JButton jButton_NetHaiChamGach;
    private javax.swing.JButton jButton_Quay;
    private javax.swing.JButton jButton_TinhTien;
    private javax.swing.JButton jButton_VeDiem;
    private javax.swing.JButton jButton_VeDoanThang;
    private javax.swing.JButton jButton_VeDuongTron;
    private javax.swing.JButton jButton_VeEllipse;
    private javax.swing.JButton jButton_VeHinhChop;
    private javax.swing.JButton jButton_VeHinhChuNhat;
    private javax.swing.JButton jButton_VeHinhHop;
    private javax.swing.JButton jButton_VeMuiTen;
    private javax.swing.JButton jButton_VeNetDut;
    private javax.swing.JButton jButton_VeTamGiac;
    private javax.swing.JButton jButton_Xoa2D;
    private javax.swing.JButton jButton_Xoa3D;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_3D;
    private javax.swing.JPanel jPanel_BT2D;
    private javax.swing.JPanel jPanel_KhungVe2D;
    private javax.swing.JPanel jPanel_KhungVe3D;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane_Menu2D;
    private javax.swing.JTabbedPane jTabbedPane_MenuChinh;
    private javax.swing.JTextArea jTextArea_ToaDo;
    private javax.swing.JTextField jTextField_a;
    private javax.swing.JTextField jTextField_b;
    private javax.swing.JTextField jTextField_canh;
    private javax.swing.JTextField jTextField_r;
    private javax.swing.JTextField jTextField_x;
    private javax.swing.JTextField jTextField_x1;
    private javax.swing.JTextField jTextField_x2;
    private javax.swing.JTextField jTextField_xC;
    private javax.swing.JTextField jTextField_xDinh;
    private javax.swing.JTextField jTextField_xO;
    private javax.swing.JTextField jTextField_y;
    private javax.swing.JTextField jTextField_y1;
    private javax.swing.JTextField jTextField_y2;
    private javax.swing.JTextField jTextField_yC;
    private javax.swing.JTextField jTextField_yDinh;
    private javax.swing.JTextField jTextField_yO;
    // End of variables declaration//GEN-END:variables
}
